### ISSUE TITLE
声音克隆速度慢，请问有llm,flow阶段推理优化建议吗？

### ISSUE THREAD

**Issue by wqzh** [FunAudioLLM/CosyVoice#100]
使用一段参考音频进行声音克隆， A800-80G显卡，llm, flow, hift 3个模型的推理时间如下：
llm: 5.39, flow: 1.69, hift: 0.07, sum: 7.16 s
llm: 6.93, flow: 2.91, hift: 0.08, sum: 9.92 s

模型大小
llm: 1.2GB, flow: 401MB, hift: 79MB

可以看到，llm和flow阶段消耗了大量的时间。请问各位大佬有什么推理优化建议吗？
我个人的想法（天马行空，不知道是否可行）：（1）量化int8, bf16;   (2) 使用vllm等推理框架  （3）cuda complie

求各位大佬尽快提交pr

**Comment by aluminumbox** [comment]
we may work on it later, but not now

**Comment by sirius-ai** [comment]
![image](https://github.com/user-attachments/assets/67297ff3-2c6e-47e8-96d3-0b546af3f0b6)
分析了一下代码，这段循环消耗了大量推理时间，且是串行的，有什么好方法加速吗？

**Comment by Erickrus** [comment]
输入是 att_cache, cnn_cache 看起来这是autoregressive的 ...

**Comment by Erickrus** [comment]
https://github.com/FunAudioLLM/CosyVoice/blob/6be8d0fc367f48c46a671edc16a99b9728038cb7/cosyvoice/llm/llm.py#L195

看起来是auto-regressive的模型

**Comment by lucasjinreal** [comment]
可有优化思路？

**Comment by wang-TJ-20** [comment]
有优化的思路了嘛

**Comment by hjj-lmx** [comment]
> 有优化的办法了

怎么优化的
