### ISSUE TITLE
How sft on a new voice with English?

### ISSUE THREAD

**Issue by MonolithFoundation** [FunAudioLLM/CosyVoice#102]
Hi, I want finetune the model with a English speaker's voice, and want make it work in other launguage as well.

I tried zero shot, it's good, but cross langual is not good, is there any suggestions on how to comes up a new voice with my data? (so that I don't need prompt, and this model can produce extremly same voice like that spkear, for all launguages)

**Comment by MonolithFoundation** [comment]
BTW, my voice just a bout 80 samples ( each of them are about 10-30seconds).

**Comment by aluminumbox** [comment]
prepare at least 1h for each speaker

**Comment by MonolithFoundation** [comment]
oh didn't have that much data



---- Replied Message ----
| From | Xiang ***@***.***> |
| Date | 07/11/2024 18:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [FunAudioLLM/CosyVoice] How sft on a new voice with English? (Issue #102) |

prepare at least 1h for each speaker
