### ISSUE TITLE
What is the benefit to introduce the masked mel condition into the flow modeling?

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#104]
Hi,  I had read in the paper that there are four condition signals to train the flow module.  the speaker embddding, the S3 tokens,  the masked mel and the intermidieate state on the density path.  I do not understand what is the masked mel condition used to?  the flow model is not autoregressively to generate mels one by one, Why there need a masked mel condition as training input?  and what is the masked mel from during inference?  Thanks.

**Comment by aluminumbox** [comment]
mel is used during zero shot inference, prompt mel will be used as  mel condition
