### ISSUE TITLE
请问训练部分的代码计划上传吗？

### ISSUE THREAD

**Issue by hongwen-sun** [FunAudioLLM/CosyVoice#107]
仓库里没有看到训练部分的代码，现有的部分训练相关代码错误很多，一些基本的训练部分都是错误的，请问有计划上传训练部分的代码吗

**Comment by aluminumbox** [comment]
see example/run.sh, it is already verified

**Comment by hongwen-sun** [comment]
> see example/run.sh, it is already verified

这里只有llm的训练，后续会开放flow的吗？我指的是flow部分训练的代码是有问题的
