### ISSUE TITLE
会上传flow训练部分代码吗？

### ISSUE THREAD

**Issue by hongwen-sun** [FunAudioLLM/CosyVoice#109]
仓库里没有看到flow训练的代码，现有的flow部分训练相关代码错误很多，一些基本的训练部分都是错误的，请问有计划上传训练flow部分的代码吗

**Comment by aluminumbox** [comment]
its already in the repo, just change llm to flow in run.sh stage 5, it is already verified

**Comment by hongwen-sun** [comment]
#79 那这个地方后续还会更新吗
