### ISSUE TITLE
后续会支持Windows么？

### ISSUE THREAD

**Issue by CyberWon** [FunAudioLLM/CosyVoice#11]
目前看到限制python3.8 linux平台

**Comment by aluminumbox** [comment]
有docker支持，windows镜像部署即可，这个是python的运行环境

**Comment by hotdogarea** [comment]
> 有docker支持，windows镜像部署即可，这个是python的运行环境

镜像在哪里 佬 ，直接原版部署会遇到deepspeed的问题，确实不支持windows
https://github.com/FunAudioLLM/CosyVoice/issues/14

**Comment by aluminumbox** [comment]
check #31  for windows usage

**Comment by CyberWon** [comment]
刘悦大佬出马，哈哈哈。
