### ISSUE TITLE
bug反馈，1.语言标签不生效 2.输出会截掉句号后面的内容

### ISSUE THREAD

**Issue by Simon-chai** [FunAudioLLM/CosyVoice#117]
暂时遇到两个问题：
1.zero-shot的时候，当promt音频是口音比较重的普通话时，输出直接就是粤语了。开头指定了<|zh|>也没用。我的promt语音就是周立齐语音包
2.输入文字只TTS生成到第一个句号之前的。后面不继续生成了。

**Comment by aluminumbox** [comment]
1. this is not bug, the model have never seen such case when prompt audio is corner case
2. you can split it into short sentence manually. systhesis speech separately if possible.

**Comment by Simon-chai** [comment]
> 1. this is not bug, the model have never seen such case when prompt audio is corner case

But the model actually know something. The accent of 周立齐 sound like Cantonese indeed. But to my opinion,promt should play a role of tips,should not be so determinative,at least should not more determinative than input text.

**Comment by Simon-chai** [comment]
> 2\. you can split it into short sentence manually. systhesis speech separately if possible.
As long as I make my input only contain comma,everything is fine.But I think CosyVoice can do better. Maybe one day you can controll pause duration or emotion by punctuation,so this will be a problem in that day. Just a little advice. BTW,the CosyVoice surprive me in it's sound likeness!
