### ISSUE TITLE
非常棒的项目，想问一下都支持什么情绪和语气呀？

### ISSUE THREAD

**Issue by daoliangai** [FunAudioLLM/CosyVoice#119]
能否列举一下支持的情绪和语气，比如我使用sad的时候出现的不是悲伤的语气，而是读出sad。

**Comment by LeesimEverglow** [comment]
如果使用接口模式，依赖模型库CosyVoice-300M-Instruct 

需要使用
def inference_instruct(self, tts_text, spk_id, instruct_text)

在instruct_text 传入情绪
