### ISSUE TITLE
unzip resource.zip file error

### ISSUE THREAD

**Issue by uestc-lxp** [FunAudioLLM/CosyVoice#13]
![image](https://github.com/FunAudioLLM/CosyVoice/assets/44855426/23d6750c-3342-47e1-9097-844c9582bc1a)

how to process it?

**Comment by HaxxorCialtion** [comment]
I have just encountered this issue and you can manually download this zip file in [https://www.modelscope.cn/models/speech_tts/speech_kantts_ttsfrd/file/view/master?fileName=resource.zip&status=2](url)

**Comment by aluminumbox** [comment]
> ![image](https://private-user-images.githubusercontent.com/44855426/346239132-23d6750c-3342-47e1-9097-844c9582bc1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMjY5NTMsIm5iZiI6MTcyMDIyNjY1MywicGF0aCI6Ii80NDg1NTQyNi8zNDYyMzkxMzItMjNkNjc1MGMtMzM0Mi00N2UxLTkwOTctODQ0Yzk1ODJiYzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAwNDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3M2QxZWUxZTNjZjQ2YzJjMzZjYWJkMjliYzE1YjY5MzcyYzBjY2IyMGZmYWEyM2Q1MWY4YjkxZjUwZmRjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mmPZ4KbsTa1iOdxb9LBo8A8sILvy4YmtUEVxT8HSv34)
> 
> how to process it?

install git lfs before git clone according to README

**Comment by Lsnsh** [comment]
Remove `pretrained_models` folder files, then install `git-lfs` work normal for me.

https://git-lfs.com/
https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage
