### ISSUE TITLE
Streaming support?

### ISSUE THREAD

**Issue by johnwick123f** [FunAudioLLM/CosyVoice#130]
**Is your feature request related to a problem? Please describe.**
The cosyvoice models are amazing but it would be great to have streaming support for real time generation.

**Describe the solution you'd like**
Streaming support for Cosyvoice models

**Describe alternatives you've considered**
I don’t believe there is another alternative for real time generation with Cosyvoice models. 

**Additional context**
I don’t have any other context

**Comment by aluminumbox** [comment]
not yet, we are working on fixing bug yet, also the released flow matching model is trained in non-causal way, we may do streaming support later

**Comment by johnwick123f** [comment]
Alright thanks for answering, great project btw!

**Comment by lucasjinreal** [comment]
Is the streaming can be supported now?
