### ISSUE TITLE
deepspeed安装失败

### ISSUE THREAD

**Issue by hotdogarea** [FunAudioLLM/CosyVoice#14]
权限已经给足了，miniconda中也设置了权限，还是出现这个问题，有出现同样问题的大哥吗  我查了目录，并没有找到对应的pip-install-6nshc3v0目录存在，或是已经被remove掉了
![image](https://github.com/FunAudioLLM/CosyVoice/assets/11146882/d1615fbd-1d19-4d34-881c-26791cc16407)
![image](https://github.com/FunAudioLLM/CosyVoice/assets/11146882/5589105b-98b0-49ec-b424-fa72cfd6aee1)

(cosy) H:\AIaudio_Live\cosyvoice\CosyVoice>pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://download.pytorch.org/whl/cu118
Collecting conformer==0.3.2 (from -r requirements.txt (line 2))
  Using cached https://mirrors.aliyun.com/pypi/packages/3f/7d/714601ab8d790d77d4158af743895fb999216cb02fc6283ab8e54911a887/conformer-0.3.2-py3-none-any.whl (4.3 kB)
Collecting deepspeed==0.14.2 (from -r requirements.txt (line 3))
  Using cached https://mirrors.aliyun.com/pypi/packages/f0/84/a7b8ff287f7e1a5f01a010880b0bc5e58f718eaca784b4be592034eab3de/deepspeed-0.14.2.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-6nshc3v0\deepspeed_b7a9ce2f848f4d0b81eaf02517880495\setup.py", line 222, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-6nshc3v0\deepspeed_b7a9ce2f848f4d0b81eaf02517880495\setup.py", line 214, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] 拒绝访问。: '.\\deepspeed\\ops\\csrc'

我去https://github.com/microsoft/DeepSpeed/issues/1189  他们那里看了，貌似windows环境支持得不是很好？得用linux部署或者WSL？

**Comment by Hwangkop** [comment]
不支持windows

**Comment by Hwangkop** [comment]
[装倒是可以装](https://blog.csdn.net/weixin_43935971/article/details/139435382)

**Comment by hotdogarea** [comment]
> [装倒是可以装](https://blog.csdn.net/weixin_43935971/article/details/139435382)

我看到了，我虚拟环境并没有使用超过3.9的python版本，用的是官方推荐的3.8环境，并且 官方requirements需要的是0.14.2版本的deepspeed

**Comment by Tanmeifanguu** [comment]
我也遇到这个情况：Collecting deepspeed==0.14.2 (from -r requirements.txt (line 3))
  Downloading https://mirrors.aliyun.com/pypi/packages/f0/84/a7b8ff287f7e1a5f01a010880b0bc5e58f718eaca784b4be592034eab3de/deepspeed-0.14.2.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JT\AppData\Local\Temp\pip-install-elg2n1xo\deepspeed_52150a2aee8142deb3408d916e3c2a35\setup.py", line 222, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\JT\AppData\Local\Temp\pip-install-elg2n1xo\deepspeed_52150a2aee8142deb3408d916e3c2a35\setup.py", line 214, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] 拒绝访问。: '.\\deepspeed\\ops\\csrc'
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      Install Ops={'deepspeed_not_implemented': 1, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
装到deepseed就出错，把这个依赖包单独下载下来安装依然出错

**Comment by Hwangkop** [comment]
> > [装倒是可以装](https://blog.csdn.net/weixin_43935971/article/details/139435382)
> 
> 我看到了，我虚拟环境并没有使用超过3.9的python版本，用的是官方推荐的3.8环境，并且 官方requirements需要的是0.14.2版本的deepspeed，回头再试试这篇文章中说的，老哥你装好了吗

win11 WSL 装好了

**Comment by hotdogarea** [comment]
直接用windows➕wsl部署吧 我已经搞定了&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tanmeifanguu ***@***.***&gt;
发送时间: 2024年7月6日 14:22
收件人: FunAudioLLM/CosyVoice ***@***.***&gt;
抄送: hotdogarea ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[FunAudioLLM/CosyVoice] deepspeed安装失败 (Issue #14)





 
我也遇到这个情况：Collecting deepspeed==0.14.2 (from -r requirements.txt (line 3))
 Downloading https://mirrors.aliyun.com/pypi/packages/f0/84/a7b8ff287f7e1a5f01a010880b0bc5e58f718eaca784b4be592034eab3de/deepspeed-0.14.2.tar.gz (1.3 MB)
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.2 MB/s eta 0:00:00
 Preparing metadata (setup.py) ... error
 error: subprocess-exited-with-error
 
× python setup.py egg_info did not run successfully.
 │ exit code: 1
 ╰─&gt; [12 lines of output]
 fatal: not a git repository (or any of the parent directories): .git
 Traceback (most recent call last):
 File "", line 2, in 
 File "", line 34, in 
 File "C:\Users\JT\AppData\Local\Temp\pip-install-elg2n1xo\deepspeed_52150a2aee8142deb3408d916e3c2a35\setup.py", line 222, in 
 create_dir_symlink('..\..\csrc', '.\deepspeed\ops\csrc')
 File "C:\Users\JT\AppData\Local\Temp\pip-install-elg2n1xo\deepspeed_52150a2aee8142deb3408d916e3c2a35\setup.py", line 214, in create_dir_symlink
 os.remove(dest)
 PermissionError: [WinError 5] 拒绝访问。: '.\deepspeed\ops\csrc'
 [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
 DS_BUILD_OPS=1
 Install Ops={'deepspeed_not_implemented': 1, 'deepspeed_ccl_comm': 1, 'deepspeed_shm_comm': 1, 'cpu_adam': 1, 'fused_adam': 1}
 [end of output]
 
note: This error originates from a subprocess, and is likely not a problem with pip.
 error: metadata-generation-failed
 装到deepseed就出错，把这个依赖包单独下载下来安装依然出错

**Comment by aluminumbox** [comment]
deepspeed is no longer needed in windows, update repo and reinstall
