### ISSUE TITLE
where is the BPE tokenizer model used in CosyVoice

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#143]
I read from paper that CosyVocie use BEP to tokenize text inputs. it has a 51886 dict size, but I did not find where to get the BPE model, where can I get it ?

**Comment by aluminumbox** [comment]
see cosyvoice.yaml for tokenizer

**Comment by JohnHerry** [comment]
> see cosyvoice.yaml for tokenizer

Yes, I  had seen in cosyvoice.yaml that it use whisper installed tokenizer, but the whisper multilingual tokenzier contains only 50256 tokens in its .tiktoken file, while in CosyVoice yaml config,  the "text_token_size" is set as 51866,  there are more tokens in cosyvoice,  So I had thought that you have your self-version BPE.

**Comment by JohnHerry** [comment]
Get it, the extra tokens are from whisper.
