### ISSUE TITLE
支持流式的TTS输出吗

### ISSUE THREAD

**Issue by rximg** [FunAudioLLM/CosyVoice#15]
很棒的工作，有像fish-speech那种支持流式的tts输出吗，加快数字人说话的反应时间。

**Comment by aluminumbox** [comment]
hmm we only provided basic train and inference, we may consider streaming output if we have extra hands

**Comment by chenxu126** [comment]
哈哈，看出来意思就是不可能

**Comment by yuyun2000** [comment]
> 哈哈，看出来意思就是不可能

你那里看出来不可能了...人家都说了人手不够
