### ISSUE TITLE
inference_sft 与 inference_zero_shot

### ISSUE THREAD

**Issue by TinaChen95** [FunAudioLLM/CosyVoice#151]
请问如何理解这两种推理方式的差异呢？

个人理解，zeroshot采用续写模式，而sft则是直接从0开始生成。

尝试了一下微调模型，并且微调后的模型在zeroshot模式下效果优于zeroshot，这是否符合预期呢？
理论上，zeroshot模式提供更多上下文，是否总是这种推断模式效果会更好？

什么情况下，应当使用zeroshot，什么情况应当使用sft模式呢？

**Comment by aluminumbox** [comment]
zero shot mode also use the embedding from the prompt audio, but sft mode use global speaker embedding from many utterance
