### ISSUE TITLE
Bad Flow Training Result

### ISSUE THREAD

**Issue by my-yy** [FunAudioLLM/CosyVoice#158]
Hello,

Thank you for releasing this awesome project.

I am trying to train the flow matching model from scratch on LibriTTS. Specifically, I am using the cosyvoice.fromscratch.yaml configuration (with lr=0.001) to train the flow model on the LibriTTS-train-clean-100h dataset.

However, I encountered some issues:

The model's performance deteriorates around 20k steps. You can see the training log here: [Training Log](https://wandb.ai/huacishu/cosyvoice/runs/0s5ex1sp).

When I used a 10k checkpoint to generate audio, the resulting waveform sounded noisy and was of low quality. You can listen to the generated wave here: [Generated Wave](https://wandb.ai/huacishu/cosyvoice/runs/g9csz77d).

I noticed that your paper mentions using Classifier-Free Guidance for training, but I couldn't find the corresponding code implementation in the repository. Could the absence of this component be causing the issue?

Thank you for your assistance!

Best regards

**Comment by aluminumbox** [comment]
your trained wav is definitely different with our validation result on libritts. check https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow_matching.py#L130 for cfg training. 
My bad I haven't updated flow config for training from scratch. You should reduce flow model size in order to converge on libritts.  change flow config num_blocks: 6 to 3, linear_units: 2048 to 1024. I will update our validated flow config later.

**Comment by my-yy** [comment]
Maybe I used an early code version.  I will clone the latest version and try the new config. Thanks for your help.

**Comment by my-yy** [comment]
Thank you very much, it works!

However, I have another question. Why is the condition in the training code set to all zeros? Shouldn't it be the masked mel spectrum?

https://github.com/FunAudioLLM/CosyVoice/blob/47dec8d2bc80132c148980d18fc83d496f86672f/cosyvoice/flow/flow.py#L79


Your trained wav is definitely different from our validation result on LibriTTS. Check [flow_matching.py#L130](https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow_matching.py#L130) for the cfg training. My bad, I haven't updated the flow config for training from scratch. You should reduce the flow model size to converge on LibriTTS. Change the flow config num_blocks from 6 to 3, and linear_units from 2048 to 1024. I will update our validated flow config later.

**Comment by aluminumbox** [comment]
I have updated cosyvoice.fromscratch.yaml, it has the flow matching config that we have validated on libritts.  I tried to mask the condition mel when training (randomly mask its initial 0 to 30% percent mel), but the result is worse on libritts. Maybe this mel condition mask trick is not so stable on libritts.

**Comment by zhangyike** [comment]
> > I have updated cosyvoice.fromscratch.yaml, it has the flow matching config that we have validated on libritts. I tried to mask the condition mel when training (randomly mask its initial 0 to 30% percent mel), but the result is worse on libritts. Maybe this mel condition mask trick is not so stable on libritts.
> 
> I trained a flow model from scratch, but in zeroshot mode, the generated audio is purely noise. Is it related to the trick that sets the conds to zeros?
> 
> https://github.com/FunAudioLLM/CosyVoice/blob/47dec8d2bc80132c148980d18fc83d496f86672f/cosyvoice/flow/flow.py#L79

In SFT mode, the generated audio sounds fine.

**Comment by aluminumbox** [comment]
> > > I have updated cosyvoice.fromscratch.yaml, it has the flow matching config that we have validated on libritts. I tried to mask the condition mel when training (randomly mask its initial 0 to 30% percent mel), but the result is worse on libritts. Maybe this mel condition mask trick is not so stable on libritts.
> > 
> > 
> > I trained a flow model from scratch, but in zeroshot mode, the generated audio is purely noise. Is it related to the trick that sets the conds to zeros?
> > https://github.com/FunAudioLLM/CosyVoice/blob/47dec8d2bc80132c148980d18fc83d496f86672f/cosyvoice/flow/flow.py#L79
> 
> In SFT mode, the generated audio sounds fine.

sorry I have only validated the inference result in sft mode. yes we should also randomly mask input during training. currently you can set the conds to zero in inference mode to solve this. we will fix it later.

**Comment by zhangyike** [comment]
> > > > I have updated cosyvoice.fromscratch.yaml, it has the flow matching config that we have validated on libritts. I tried to mask the condition mel when training (randomly mask its initial 0 to 30% percent mel), but the result is worse on libritts. Maybe this mel condition mask trick is not so stable on libritts.
> > > 
> > > 
> > > I trained a flow model from scratch, but in zeroshot mode, the generated audio is purely noise. Is it related to the trick that sets the conds to zeros?
> > > https://github.com/FunAudioLLM/CosyVoice/blob/47dec8d2bc80132c148980d18fc83d496f86672f/cosyvoice/flow/flow.py#L79
> > 
> > 
> > In SFT mode, the generated audio sounds fine.
> 
> sorry I have only validated the inference result in sft mode. yes we should also randomly mask input during training. currently you can set the conds to zero in inference mode to solve this. we will fix it later.

Thanks, it works for me.

**Comment by taalua** [comment]
HI, how do you solve this issue? what code modification need to be done? Thanks

**Comment by aluminumbox** [comment]
> HI, how do you solve this issue? what code modification need to be done? Thanks

update code, this bug is already fixed

**Comment by JohnHerry** [comment]
execuse me, I saw that the flow-maching model,   feat_len = (token_len / 50 * 22050/256).int(); is it means that the flow model config just for 22.05Khz audios?   we want to train the flow from scratch, but our dataset is  16K hz audios and mel-specs,   will that make bad result? I mean we do only train the flow module, but keep the LLM part and HiFiGAN part unchanged.    
I guess that  we can make some change here to fit the 16Khz mels as well, but  I am not sure if our 16Khz trained flow mode, its output can be used for the HiFiGAN part then.
