### ISSUE TITLE
no module named 'matcha.models'.

### ISSUE THREAD

**Issue by ldxbxl** [FunAudioLLM/CosyVoice#17]
当我按照readme中步骤安装了环境下载了模型然后运行export PYTHONPATH=third_party/AcademiCodec:third_party/Matcha-TTS和from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav
import torchaudio

cosyvoice = CosyVoice('speech_tts/CosyVoice-300M-SFT')
# sft usage
print(cosyvoice.list_avaliable_spks())
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
torchaudio.save('sft.wav', output['tts_speech'], 22050)

cosyvoice = CosyVoice('speech_tts/CosyVoice-300M')
# zero_shot usage
prompt_speech_16k = load_wav('zero_shot_prompt.wav', 16000)
output = cosyvoice.inference_zero_shot('收到好友从远方寄来的生日礼物，那份意外的惊喜与深深的祝福让我心中充满了甜蜜的快乐，笑容如花儿般绽放。', '希望你以后能够做的比我还好呦。', prompt_speech_16k)
torchaudio.save('zero_shot.wav', output['tts_speech'], 22050)
# cross_lingual usage
prompt_speech_16k = load_wav('cross_lingual_prompt.wav', 16000)
output = cosyvoice.inference_cross_lingual('<|en|>And then later on, fully acquiring that company. So keeping management in line, interest in line with the asset that\'s coming into the family is a reason why sometimes we don\'t buy the whole thing.', prompt_speech_16k)
torchaudio.save('cross_lingual.wav', output['tts_speech'], 22050)

cosyvoice = CosyVoice('speech_tts/CosyVoice-300M-Instruct')
# instruct usage
output = cosyvoice.inference_instruct('在面对挑战时，他展现了非凡的<strong>勇气</strong>与<strong>智慧</strong>。', '中文男', 'Theo \'Crimson\', is a fiery, passionate rebel leader. Fights with fervor for justice, but struggles with impulsiveness.')
torchaudio.save('instruct.wav', output['tts_speech'], 22050)会报错raceback (most recent call last):
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/media/user/E/CosyVoice-main/cosyvoice/flow/flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package

During handling of the above exception, another exception occurred:
 cosyvoice = CosyVoice('speech_tts/CosyVoice-300M-SFT')
  File "/media/user/E/CosyVoice-main/cosyvoice/cli/cosyvoice.py", line 29, in __init__
    configs = load_hyperpyyaml(f)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/pydoc.py", line 1626, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/home/user/anaconda3/envs/cosyvoice/lib/python3.8/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package

**Comment by hotdogarea** [comment]
我也遇到同样的问题，但我的git lfs是确认已经安装好了的
![image](https://github.com/FunAudioLLM/CosyVoice/assets/11146882/ab512225-6cb5-4ae1-8b07-b680d1ddb8c3)

**Comment by aluminumbox** [comment]
> 我也遇到同样的问题，但我的git lfs是确认已经安装好了的 ![image](https://private-user-images.githubusercontent.com/11146882/346339094-ab512225-6cb5-4ae1-8b07-b680d1ddb8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjA3MDksIm5iZiI6MTcyMDM2MDQwOSwicGF0aCI6Ii8xMTE0Njg4Mi8zNDYzMzkwOTQtYWI1MTIyMjUtNmNiNS00YWUxLThiMDctYjY4MGQxZGRiOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWU0NGQ0MjMzNDkzMDVkNTEwZjJkMDg5NTlkMGY4MTkwMDA0NDEwNmJmOTdkNmIwYTE4OWMwMzAwMGNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O96yluOETClKY1qqN1MbaUcoV2z2CY27308egOKD-pE)

check faq.md, remember export pythonpath before run python. check third_party directory.

**Comment by hotdogarea** [comment]
> > 我也遇到同样的问题，但我的git lfs是确认已经安装好了的 ![image](https://private-user-images.githubusercontent.com/11146882/346339094-ab512225-6cb5-4ae1-8b07-b680d1ddb8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjA3MDksIm5iZiI6MTcyMDM2MDQwOSwicGF0aCI6Ii8xMTE0Njg4Mi8zNDYzMzkwOTQtYWI1MTIyMjUtNmNiNS00YWUxLThiMDctYjY4MGQxZGRiOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWU0NGQ0MjMzNDkzMDVkNTEwZjJkMDg5NTlkMGY4MTkwMDA0NDEwNmJmOTdkNmIwYTE4OWMwMzAwMGNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O96yluOETClKY1qqN1MbaUcoV2z2CY27308egOKD-pE)
> 
> check faq.md, remember export pythonpath before run python. check third_party directory.
如你所说，
问题解决了，THX

**Comment by jkla139** [comment]
In jupyter notebook, I solve it by the following code:
```python
import os, sys
sys.path.insert(0, os.path.abspath('third_party/Matcha-TTS'))
```

**Comment by raimmm** [comment]
> > > 我也遇到同样的问题，但我的git lfs是确认已经安装好了的 ![image](https://private-user-images.githubusercontent.com/11146882/346339094-ab512225-6cb5-4ae1-8b07-b680d1ddb8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjA3MDksIm5iZiI6MTcyMDM2MDQwOSwicGF0aCI6Ii8xMTE0Njg4Mi8zNDYzMzkwOTQtYWI1MTIyMjUtNmNiNS00YWUxLThiMDctYjY4MGQxZGRiOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWU0NGQ0MjMzNDkzMDVkNTEwZjJkMDg5NTlkMGY4MTkwMDA0NDEwNmJmOTdkNmIwYTE4OWMwMzAwMGNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O96yluOETClKY1qqN1MbaUcoV2z2CY27308egOKD-pE)
> > 
> > 
> > check faq.md, remember export pythonpath before run python. check third_party directory.
> > 如你所说，
> > 问题解决了，THX

按照这个方式后还是有同样的错误，求解答

**Comment by ldxbxl** [comment]
> > > > 我也遇到同样的问题，但我的git lfs是确认已经安装好了的 ![image](https://private-user-images.githubusercontent.com/11146882/346339094-ab512225-6cb5-4ae1-8b07-b680d1ddb8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjA3MDksIm5iZiI6MTcyMDM2MDQwOSwicGF0aCI6Ii8xMTE0Njg4Mi8zNDYzMzkwOTQtYWI1MTIyMjUtNmNiNS00YWUxLThiMDctYjY4MGQxZGRiOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWU0NGQ0MjMzNDkzMDVkNTEwZjJkMDg5NTlkMGY4MTkwMDA0NDEwNmJmOTdkNmIwYTE4OWMwMzAwMGNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O96yluOETClKY1qqN1MbaUcoV2z2CY27308egOKD-pE)
> > > 
> > > 
> > > check faq.md, remember export pythonpath before run python. check third_party directory.
> > > 如你所说，
> > > 问题解决了，THX
> 
> 按照这个方式后还是有同样的错误，求解答

我也是安装了git lfs，且在运行代码之前加了export PYTHONPATH=third_party/Matcha-TTS，但是还是相同的报错，请问还需要将什么添加到路径中吗？

**Comment by raimmm** [comment]
> > > > > 我也遇到同样的问题，但我的git lfs是确认已经安装好了的 ![image](https://private-user-images.githubusercontent.com/11146882/346339094-ab512225-6cb5-4ae1-8b07-b680d1ddb8c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjA3MDksIm5iZiI6MTcyMDM2MDQwOSwicGF0aCI6Ii8xMTE0Njg4Mi8zNDYzMzkwOTQtYWI1MTIyMjUtNmNiNS00YWUxLThiMDctYjY4MGQxZGRiOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWU0NGQ0MjMzNDkzMDVkNTEwZjJkMDg5NTlkMGY4MTkwMDA0NDEwNmJmOTdkNmIwYTE4OWMwMzAwMGNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O96yluOETClKY1qqN1MbaUcoV2z2CY27308egOKD-pE)
> > > > 
> > > > 
> > > > check faq.md, remember export pythonpath before run python. check third_party directory.
> > > > 如你所说，
> > > > 问题解决了，THX
> > 
> > 
> > 按照这个方式后还是有同样的错误，求解答
> 
> 我也是安装了git lfs，且在运行代码之前加了export PYTHONPATH=third_party/Matcha-TTS，但是还是相同的报错，请问还需要将什么添加到路径中吗？

我也是同样的问题

**Comment by yangcunning1** [comment]
我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下

**Comment by hotdogarea** [comment]
这里其实就是环境变量的问题 我是在ubuntu下 可以在代码执行前运行export&nbsp;PYTHONPATH
也可以直接去修改 user目录下 .bashrc文件

发自我的iPhone


------------------ Original ------------------
From: raimmm ***@***.***&gt;
Date: Mon,Jul 8,2024 10:52 AM
To: FunAudioLLM/CosyVoice ***@***.***&gt;
Cc: hotdogarea ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [FunAudioLLM/CosyVoice] no module named 'matcha.models'. (Issue#17)





      
我也遇到同样的问题，但我的git lfs是确认已经安装好了的 
  
check faq.md, remember export pythonpath before run python. check third_party directory.
 如你所说，
 问题解决了，THX
   
按照这个方式后还是有同样的错误，求解答
  
我也是安装了git lfs，且在运行代码之前加了export PYTHONPATH=third_party/Matcha-TTS，但是还是相同的报错，请问还需要将什么添加到路径中吗？
  
我也是同样的问题

**Comment by cpken** [comment]
```shell
$ pip install peft
$ cd CosyVoice/third_party/
$ git clone https://github.com/shivammehta25/Matcha-TTS
```

**Comment by cpken** [comment]
请确保你的路径是 `CosyVoice-main/third_party/Matcha-TTS/` ，我的 ubuntu 按照此路径，可以正常加载。

**Comment by 13140438775** [comment]
pip install matcha-tts  自己安装依赖

**Comment by GUUser91** [comment]
I had a similar problem when I tried to launch the webui.py file. I was able to solve the problem by using a 3.10 virutal environment.

**Comment by ApplePie420** [comment]
I've happened to run into this exact problem while trying to run CosyVoice from a bash script using 
```bash
conda run -n cosyvoice --live-stream python3 CosyVoice/generate.py "$1" "$2"
```

It executed, but ended on the same error as OP. I have found the solution on [this website](https://blog.csdn.net/weighless/article/details/140696100), and basically it requires you to export the Matcha-TTS library to `pythonpath`, like so:

```bash
export PYTHONPATH=/home/user/ai/CosyVoice/third_party/Matcha-TTS:$PYTHONPATH
conda run -n cosyvoice --live-stream python3 CosyVoice/generate.py "$1" "$2"
```

replace the path with whatever your location of CosyVoice folder is.

**Comment by qq36545** [comment]
在项目根目录执行：git submodule update --init --recursive

来自：https://github.com/FunAudioLLM/CosyVoice/issues/942
