### ISSUE TITLE
pip install error, under win10

### ISSUE THREAD

**Issue by reinmj** [FunAudioLLM/CosyVoice#18]
(cosyvoice) PS J:\githubs\CosyVoice> pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://download.pytorch.org/whl/cu118
Collecting conformer==0.3.2 (from -r requirements.txt (line 2))
  Downloading https://mirrors.aliyun.com/pypi/packages/3f/7d/714601ab8d790d77d4158af743895fb999216cb02fc6283ab8e54911a887/conformer-0.3.2-py3-none-any.whl (4.3 kB)
Collecting deepspeed==0.14.2 (from -r requirements.txt (line 3))
  Downloading https://mirrors.aliyun.com/pypi/packages/f0/84/a7b8ff287f7e1a5f01a010880b0bc5e58f718eaca784b4be592034eab3de/deepspeed-0.14.2.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 663.4 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mac\AppData\Local\Temp\pip-install-tuexzav1\deepspeed_d61cae8dc0c942e1827f90d08a2215a1\setup.py", line 148, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by reinmj** [comment]
> hmmm you can consider loose the requirement constraint, for example in requirements change deepspeed==0.14.2 to deepspeed嗯，你可以考虑放宽需求约束，例如在需求中将 deepSpeed==0.14.2 更改为 DeepSpeed

no works.

**Comment by aluminumbox** [comment]
> > hmmm you can consider loose the requirement constraint, for example in requirements change deepspeed==0.14.2 to deepspeed嗯，你可以考虑放宽需求约束，例如在需求中将 deepSpeed==0.14.2 更改为 DeepSpeed
> 
> no works.

update repo, deepspeed is no longer needed in windows
