### ISSUE TITLE
question about traing of cosyvoice

### ISSUE THREAD

**Issue by UestcJay** [FunAudioLLM/CosyVoice#183]
Thank you for your open source, which benefits the community. I have some training-related questions. When training Cosyvoice, are llm, flow, and hifigan trained together? Or should llm and flow be trained separately? It feels like there is nothing written in the report.
![微信截图_20240722122015](https://github.com/user-attachments/assets/97cbf0b3-c26c-4cf3-bc3a-980a92fded7f)

**Comment by aluminumbox** [comment]
yes we train them separately, but of course you can try to train them jointly, maybe it performs better, but of course harder to code
