### ISSUE TITLE
The concatenation handling of kv_cache causes a significant time consumption (18%)

### ISSUE THREAD

**Issue by hexisyztem** [FunAudioLLM/CosyVoice#184]
I conducted a profile analysis of the inference process and found that the CatArrayBatchedCopy kernel has a high time consumption ratio. After checking the calculation logic, I suspect that this time consumption may be due to improper handling of kv_cache. 
https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/transformer/attention.py#L299

Tool: [NVIDIA Nsight Systems](https://developer.nvidia.com/nsight-systems)

**Comment by hexisyztem** [comment]
![image](https://github.com/user-attachments/assets/43d82da5-ee94-49e5-81df-9f9c1ed04839)

**Comment by hexisyztem** [comment]
By the way, is there a cosyvoice base model that uses multihead attention?

**Comment by aluminumbox** [comment]
https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/transformer/attention.py#L299 concat the history attention with current frame, but I also don't know why this has so much computation cost. add me 铝箱 in dingding group to talk about details
