### ISSUE TITLE
Instruct合成和跨语种合成的一些疑问

### ISSUE THREAD

**Issue by yzliu90** [FunAudioLLM/CosyVoice#187]
首先感谢开源你们的工作，我有以下几个疑问：
1、观察到在跨语种合成时，在text前加入语种标签，如<|zh|>，可以通过zero-shot的方式，进行跨语种合成，其实这就是sft的合成方式吧？
2、instruct合成时，llm的输入不再使用embedding，是有什么特别考虑吗？如果用了xvector，能够实现风格迁移？
3、微调之后，观察到zero_shot合成音比sft合成音，音量小很多，这是为什么？

**Comment by aluminumbox** [comment]
1. yes
2. embedding will influence instruct in our experiment
3. during sft, use spk embedding for the sft speaker. I have no clue for the volume issue either

**Comment by yzliu90** [comment]
感谢回复！有几个问题请在确认一下。
1、也就是说，在instruct时，如果使用embeding，会影响instruct的指导意义，其实是embeding同时携带了情感或风格信息，影响了风格迁移？
2、如果embeding接偶完美，仅保留说话人信息，理论上可以通过类似于跨语种<|language|>类似的标签实现风格的迁移？
3、在微调时，提供了两种方式，spk_embedding和utt_embedding，这两种embeding对模型效果有多大影响？建议使用哪一种？
感谢回复！
