### ISSUE TITLE
安装环境时，提示python 3.8版本太低

### ISSUE THREAD

**Issue by qiangduscu** [FunAudioLLM/CosyVoice#19]
ERROR: Ignored the following versions that require a different python version: 3.2 Requires-Python >=3.9; 3.2.1 Requires-Python >=3.9; 3.2rc0 Requires-Python >=3.9; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9; 3.8.1 Requires-Python >=3.9; 3.8.2 Requires-Python >=3.9; 3.8.3 Requires-Python >=3.9; 3.8.4 Requires-Python >=3.9; 3.9.0 Requires-Python >=3.9; 3.9.0rc2 Requires-Python >=3.9; 3.9.1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.16.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.16.0

**Comment by threadflow** [comment]
Try to use conda create -n cosyvoice python=3.10, seems work.

**Comment by aluminumbox** [comment]
I believe you are using MacOS. Please change onnxruntime-gpu==1.16 to onnxruntime in requirements.txt
