### ISSUE TITLE
TypeError: padding() missing 1 required positional argument: 'use_spk_embedding'

### ISSUE THREAD

**Issue by rlenain** [FunAudioLLM/CosyVoice#190]
**Describe the bug**
When running `bash run.sh` in the training recipe (under `examples/libritts/cosyvoice`), I get the following error: 

``` 
TypeError: padding() missing 1 required positional argument: 'use_spk_embedding'
```

**Comment by aluminumbox** [comment]
use latest yaml, it has use_spk_embedding in cosyvoice.yaml

**Comment by JohnHerry** [comment]
> use latest yaml, it has use_spk_embedding in cosyvoice.yaml

in the latest config, use_spk_embedding is false, is that means when training flow model from scratch,  we shell use the spk_embedding of current utterance instead of  a random one from the utter speaker?

**Comment by aluminumbox** [comment]
no, set use_spk_embedding to false when train base model. set to true if you want to train a sft model for a specific speaker

**Comment by JohnHerry** [comment]
> no, set use_spk_embedding to false when train base model. set to true if you want to train a sft model for a specific speaker

Yes, I means the base model of flow-matching.  which need the spk_embedding as condition.

**Comment by JohnHerry** [comment]
there are too much samples, If I can use a random spk_embedding from the same speaker, the computation of preprocessing will save a lot.

**Comment by aluminumbox** [comment]
> > no, set use_spk_embedding to false when train base model. set to true if you want to train a sft model for a specific speaker
> 
> Yes, I means the base model of flow-matching. which need the spk_embedding as condition.

no, when train base model, use utt_embedding which is extracted from current utterance. only when sft training, use spk_embedding

**Comment by JohnHerry** [comment]
> > > no, set use_spk_embedding to false when train base model. set to true if you want to train a sft model for a specific speaker
> > 
> > 
> > Yes, I means the base model of flow-matching. which need the spk_embedding as condition.
> 
> no, when train base model, use utt_embedding which is extracted from current utterance. only when sft training, use spk_embedding

get it, thanks a alot !
