### ISSUE TITLE
increment training bug

### ISSUE THREAD

**Issue by QianguoS** [FunAudioLLM/CosyVoice#197]
**Describe the bug**
When I start training, it produce error like this
’‘’
raise ImportError("There is no such entity as %s" % callable_string)
  ImportError: There is no such entity as matcha.utils.audio.mel_spectrogram
‘’‘

In fact, the error code originates from this line.

‘’‘
with open(args.config, 'r') as f:
        configs = load_hyperpyyaml(f, overrides=override_dict)
’‘’‘

**Comment by aluminumbox** [comment]
check faq.md, export PYTHONPATH
