### ISSUE TITLE
sudo apt-get install sox libsox-dev 在window 下怎么设置

### ISSUE THREAD

**Issue by anstonjie** [FunAudioLLM/CosyVoice#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aluminumbox** [comment]
check #31  for windows usage

**Comment by cacard** [comment]
我想知道是如何解决Windos SoX问题的？ 更改python和cuda等的版本？

我按官方在win下部署，出现SoX依赖问题：
pydoc.ErrorDuringImport: problem in cosyvoice.dataset.processor - RuntimeError: torchaudio.utils.sox_utils.set_buffer_size requires sox extension, but TorchAudio is not compiled with it. Please build TorchAudio with libsox support.

**Comment by cacard** [comment]
win11 run ok:
https://github.com/FunAudioLLM/CosyVoice/issues/66

**Comment by aluminumbox** [comment]
sox is no longer needed when running code
