### ISSUE TITLE
请问 extract_speech_token 这一步是否可以加速呢？

### ISSUE THREAD

**Issue by TinaChen95** [FunAudioLLM/CosyVoice#204]
想要微调，但是抽特征的速度有点慢。
请问有没有建议的加速方法呢？

目前好像写死了 batch=1 推断，这块儿是否建议修改呢？
或者转成 tensorrt 之类的，不知道是否会有加速呢

**Comment by JunityZhan** [comment]
请问你解决了吗？speech tokenizer可以调batchsize更大吗？

**Comment by csu-roycheng** [comment]
请问这个问题有解决吗

**Comment by csu-roycheng** [comment]
> 请问你解决了吗？speech tokenizer可以调batchsize更大吗？

有可能是 onnx 没用 GPU 推理的问题

**Comment by r666ay** [comment]
用gpu的话, 10h能提取960h的speech tokens(以LibriTTS为例). 但是onnx相当吃cpu, 在12cpu上同时跑2个extractor speech token的脚本, cpu利用率就100%. 建议用gpu和更多的cpu来处理.
