### ISSUE TITLE
大标题之间使用传统方法增加停顿？

### ISSUE THREAD

**Issue by LayBrick** [FunAudioLLM/CosyVoice#205]
一、国内要闻
今天是...
二、国际要闻
今天...

对于第二个大标题与前文之间停顿较小的问题，有没有什么方法可以解决
比如使用正则化的方法，强行在第二个标题开始前增加停顿

**Comment by aluminumbox** [comment]
there is no way to fix it using model yet, you can try add 0.2s blank at each sentence start
