### ISSUE TITLE
ttsfrd apple metal cpu(arm64) support

### ISSUE THREAD

**Issue by songlairui** [FunAudioLLM/CosyVoice#21]
**Is your feature request related to a problem? Please describe.** 
Wanna run cosyvoice on macbook metal cpu

**Describe the solution you'd like** 
provide `ttsfrd-0.3.6-cp38-cp38-linux_arm64.whl`

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by aluminumbox** [comment]
we will add wetextprocessing to replace ttsfrd when ttsfrd is unavaliable

**Comment by aluminumbox** [comment]
please update the repo, ttsfrd is now optional during inference
