### ISSUE TITLE
Why there are different configs between cosyvoice.yaml and cosyvoice.fromscratch.yaml

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#219]
I found in cosyvoice.yaml , the llm num_blocks is 14, while that config in cosyvoice.fromscratch.yaml Half reduced, it seems that it will get a smaller model from cosyvoice.fromscratch.yaml. Is that means the cosyvoice.fromscratch.yaml is used to train the smaller model while the cosyvoice.yaml is used to train the cosyvoide-base?

**Comment by aluminumbox** [comment]
cosyvoice.fromscratch.yaml is intended for train on libritts 960h, so it has smaller model size

**Comment by JohnHerry** [comment]
> cosyvoice.fromscratch.yaml is intended for train on libritts 960h, so it has smaller model size

Thank you very much.  I see in the paper that Cosyvoice-tiny takes 12 layers, but in the `cosyvoice.fromscrath.yaml`, its `num_blocks` is only 7,  it is even smaller then in the paper.
