### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/jiangjinlong/Documents/Tools/CosyVoice/pretrained_models/CosyVoice-300M-SFT/speech_tokenizer_v1.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by a386572631** [FunAudioLLM/CosyVoice#225]
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/jiangjinlong/Documents/Tools/CosyVoice/pretrained_models/CosyVoice-300M-SFT/speech_tokenizer_v1.onnx failed:Protobuf parsing failed.

protobuf版本4.25与requirement一致
% pip show protobuf
Name: protobuf
Version: 4.25.0
Summary: 
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /opt/homebrew/anaconda3/envs/cosyvoice/lib/python3.9/site-packages
Requires: 
Required-by: grpcio-tools, onnxruntime, tensorboard

**Comment by aluminumbox** [comment]
check faq.md, install git-lfs

**Comment by Lu7-H** [comment]
> check faq.md, install git-lfs

I meet this problem too.FAQ.md doesn't mentioned this problem,I don't know how to sovle it.And i have installed git-lfs.Can describe the method to solve this problem detailed？The Error information is 'onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed.'

**Comment by scalar27** [comment]
I get the same error.

**Comment by Lu7-H** [comment]
> I get the same error.

check your model and make it in correct size xxxM not xxxkb.

**Comment by wp558** [comment]
I also got the same error. Maybe it occurred when there was something wrong with the model file 
.onnx. So I re-downloaded the models and it worked.

**Comment by wl33thompson** [comment]
i fellow the exact instruction from the guideline in my MAC book and got the following same error. can you help?

Traceback (most recent call last):
  File "webui.py", line 190, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/Users/weishuolin/Documents/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/Users/weishuolin/Documents/CosyVoice/cosyvoice/cli/frontend.py", line 52, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/opt/anaconda3/envs/cosyvoice2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/anaconda3/envs/cosyvoice2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed.

**Comment by zhaoshuyan** [comment]
torchaudio.set_audio_backend('soundfile')
Traceback (most recent call last):
  File "/home/zsy/CosyVoice/webui.py", line 184, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/home/zsy/CosyVoice/cosyvoice/cli/cosyvoice.py", line 33, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/home/zsy/CosyVoice/cosyvoice/cli/frontend.py", line 52, in __init__
    self.campplus_session = onnxruntime.InferenceSession(campplus_model, sess_options=option, providers=["CPUExecutionProvider"])
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/envs/cosyvoice/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrained_models/CosyVoice-300M/campplus.onnx failed:Protobuf parsing failed. 同样的问题?要如何解决?另外,numpy什么时候可以支持2.0的?
