### ISSUE TITLE
官方提供的 ttsfrd 安装不上

### ISSUE THREAD

**Issue by theoldsong** [FunAudioLLM/CosyVoice#23]
(cosyvoice) E:\python\CosyVoice\pretrained_models\speech_kantts_ttsfrd>pip install ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by theoldsong** [comment]
没有支持win系统的ttsfrd吗

**Comment by aluminumbox** [comment]
no, we do not have windows ttsfrd whl. We will replace it with wetext later

**Comment by Naozumi520** [comment]
`wetext` likely won't be working? The `pynini` package it use is linux only also.

**Comment by Hwangkop** [comment]
running with WSL

**Comment by Naozumi520** [comment]
I commented those lines with ttsfrd, as the text I use can be cleaned already.

**Comment by Hello-Pig** [comment]
ubuntu 上为何也不行？
![image](https://github.com/FunAudioLLM/CosyVoice/assets/20633385/bcf4b312-f454-4817-91e3-52ea105ee325)

顺便说下，resource.zip 貌似也有问题

**Comment by zddgg** [comment]
ttsfrd 通过python sdk下载的没有这个文件
ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl
可以看下git的那个下载

**Comment by Hwangkop** [comment]
> ubuntu 上为何也不行？ ![image](https://private-user-images.githubusercontent.com/20633385/346289578-bcf4b312-f454-4817-91e3-52ea105ee325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTQ3NjEsIm5iZiI6MTcyMDMxNDQ2MSwicGF0aCI6Ii8yMDYzMzM4NS8zNDYyODk1NzgtYmNmNGIzMTItZjQ1NC00ODE3LTkxZTMtNTJlYTEwNWVlMzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAxMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTE5N2U0ZDg1OGU4MDhkNzExMDYwMzI3ODQ0NDM3N2MzMzI5OGE4NTc5MWY3MTU3ZDJmMDQ5ZDIzYjBmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9R-JrdmgrFEuIQvpLfkpDGqyMdTHC8TbmBYOASOcs-0)
> 
> 顺便说下，resource.zip 貌似也有问题

[下载地址](https://www.modelscope.cn/models/speech_tts/speech_kantts_ttsfrd/files)

**Comment by aluminumbox** [comment]
> 没有支持win系统的ttsfrd吗

please update the repo, ttsfrd is not optinal during inference.

**Comment by lilongwei5054** [comment]
我用的ubuntu20，  也报这个错 ：ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by liutianye** [comment]
ubuntu一样报了找不到这个

**Comment by jiangxia207** [comment]
ubuntu22 同顶

**Comment by aluminumbox** [comment]
check faq.md, ttsfrd is a frontend package, you can ignore it, we will replace it with wetext later

**Comment by DantesLin** [comment]
os: archlinux
python:3.11
ERROR: ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by wang-kangkang** [comment]
关键这个只提供cp38，现在用python3.8的已经属于版本很低的了吧，为什么强制用cp38

**Comment by Nojahhh** [comment]
I've been trying to find a ttsfrd package for 3.11 but I haven't been able to find any. It feels like a port from python3.8 to newer versions shouldn't be too hard, but idk. I might be wrong.

**Comment by MUcxGit** [comment]
unzip resource.zip -d .的时候报错呀,
"Either this file is not a zipfile, or it constitutes one disk of a multi-part archive".无论是.tar还是.zip都解压不了,windows下解压完放到wsl ubuntu里,初始化也报错"AssertionError: failed to initialize ttsfrd resource"
