### ISSUE TITLE
有没有什么技巧可以生成中英文混读？

### ISSUE THREAD

**Issue by fxsome** [FunAudioLLM/CosyVoice#24]
单单中文，和英文都很好。不过试了一下混读，感觉不太好。有什么技巧么？

**Comment by aluminumbox** [comment]
看看日志里，是不是前端对于中英文混读处理的有问题，如果是的话，那么可以手动调整一下中英文混合输入，毕竟前端规则无法穷举

**Comment by v-yunbin** [comment]
1. 中英混合，某个英文单词会读错，看tn处理是对的。
2. 中英混合，英文单词和英文单词间会有相对较长的停顿，整体觉得会比较突兀，比如欢迎收看HI FOUR T发布会，FOUR和T之间会停顿0.5s,可感觉衔接不自然。
有什么应对办法吗

**Comment by aluminumbox** [comment]
1.  try change FOUR to four or Four
2.  no easy solution yet

**Comment by v-yunbin** [comment]
> 1. try change FOUR to four or Four
好多了，谢谢哈哈哈哈
> 2. no easy solution yet
