### ISSUE TITLE
能提供一份阿里云的镜像吗，现在太难下载原始镜像了

### ISSUE THREAD

**Issue by xs818818** [FunAudioLLM/CosyVoice#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aluminumbox** [comment]
我们这个dockerfile是从dockerhub原始镜像编译过来的，是为了让用户能够自己增加自己的业务逻辑，可以试试开个vpn，先把基础镜像下载好
