### ISSUE TITLE
Slow Inference Speed and Potential Model Size Reduction

### ISSUE THREAD

**Issue by xddun** [FunAudioLLM/CosyVoice#261]
---

Thank you for this open-source project!

I successfully ran the code:
```python
import os, sys
import time

# Set CUDA visibility to 3
os.environ["CUDA_VISIBLE_DEVICES"] = "3"

sys.path.insert(0, os.path.abspath('third_party/Matcha-TTS'))

from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav
import torchaudio

cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
# sft usage
print(cosyvoice.list_avaliable_spks())
time1 = time.time()
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
torchaudio.save('sft.wav', output['tts_speech'], 22050)
time2 = time.time()
print(f"used time: {time2 - time1}")
```

Here is the log information:
```
2024-08-07 15:42:56,601 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-07 15:42:56,629 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 281d6cbb97624010f3a9c31ecef8a6c2 and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/ssd/xiedong/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/ssd/xiedong/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-08-07 15:43:05.997988387 [W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have a negative impact on performance. e.g. ORT explicitly assigns shape-related ops to CPU to improve perf.
2024-08-07 15:43:05.998009147 [W:onnxruntime:, session_state.cc:1164 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
load legacy transf breakmodel
load legacy transf breakmodel
text.cc: festival_Text_init
open voice lang map failed
break model index not valid
['中文女', '中文男', '日语男', '粤语女', '英文女', '英文男', '韩语女']
tn 你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？ to 你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？
used time: 7.975744962692261
```

However, I found that it took 8 seconds to generate a 12-second WAV file, which seems like a very slow inference speed. Therefore, I have a few questions and would appreciate your response:
1. Does it necessarily require such a large model to achieve good results? Have there been any attempts to create a smaller model?
2. I executed Matcha-TTS, which is an extremely fast model, but it does not support Chinese.
3. Have you trained a Chinese model for Matcha-TTS, and if so, is it effective?

---

**Comment by xddun** [comment]
https://github.com/FunAudioLLM/CosyVoice/issues/49

Using WeTextProcessing is still slow, so we probably need to rely on slimming down the model itself.

**Comment by aluminumbox** [comment]
we have no play to provide a smaller model now, but you can train a smaller model using your own data with the repo

**Comment by shaoqingyang** [comment]
I used your code
```python
import os, sys
import time

# Set CUDA visibility to 3
os.environ["CUDA_VISIBLE_DEVICES"] = "3"

sys.path.insert(0, os.path.abspath('third_party/Matcha-TTS'))

from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav
import torchaudio

cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
# sft usage
print(cosyvoice.list_avaliable_spks())
time1 = time.time()
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
torchaudio.save('sft.wav', output['tts_speech'], 22050)
time2 = time.time()
print(f"used time: {time2 - time1}")
``` 
Error is this.
Traceback (most recent call last):
  File "gen.py", line 18, in <module>
    torchaudio.save('sft.wav', output['tts_speech'], 22050)
TypeError: 'generator' object is not subscriptable
You know how to fix it?

**Comment by xddun** [comment]
> I used your code
> 
> ```python
> import os, sys
> import time
> 
> # Set CUDA visibility to 3
> os.environ["CUDA_VISIBLE_DEVICES"] = "3"
> 
> sys.path.insert(0, os.path.abspath('third_party/Matcha-TTS'))
> 
> from cosyvoice.cli.cosyvoice import CosyVoice
> from cosyvoice.utils.file_utils import load_wav
> import torchaudio
> 
> cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
> # sft usage
> print(cosyvoice.list_avaliable_spks())
> time1 = time.time()
> output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
> torchaudio.save('sft.wav', output['tts_speech'], 22050)
> time2 = time.time()
> print(f"used time: {time2 - time1}")
> ```
> 
> Error is this. Traceback (most recent call last): File "gen.py", line 18, in torchaudio.save('sft.wav', output['tts_speech'], 22050) TypeError: 'generator' object is not subscriptable You know how to fix it?

Environmental issues, these are really hard to fix. The installation process is a bit complicated.

**Comment by Ewenwan** [comment]
TypeError: 'generator' object is not subscriptable You know how to fix it?
add __next__():
torchaudio.save('sft.wav', output.__next__()['tts_speech'], 22050)
