### ISSUE TITLE
Why there is always a small noise point at the begining of generated speech on pretrained speaker in base-model

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#262]
We are trying the pretrained base-model and select the pretrained speaker defined in webui. but any speaker, any input text, the  generated speech will always starts with a small noise piece like below [ it sound like a short Electric noise]:
![smp](https://github.com/user-attachments/assets/844c1ee6-0a52-4131-8fe4-04a8a63451b5)

what is the reason? is there any sampling method to produce this piece? or this piece is just come from the CosyVoice models[LM , or Flow]？   and how to avoid such a noise?

**Comment by aluminumbox** [comment]
this is the base mode bug, during base mode training, it didn't consider the case when condition mel is all zero, you can train with our opensource code and it can fix the bug

**Comment by JohnHerry** [comment]
thank you
