### ISSUE TITLE
batch size for multi-lingual model

### ISSUE THREAD

**Issue by zhangyike** [FunAudioLLM/CosyVoice#276]
hi, I want to train a 300M LLM following the config in the CosyVoice paper. I wonder the how to set "max_frames_in_batch" and "accum_grad" in the config.

**Comment by aluminumbox** [comment]
set max_frames_in_batch according to your gpu memory, bigger max_frames_in_batch helps the training process stable

**Comment by zhangyike** [comment]
> set max_frames_in_batch according to your gpu memory, bigger max_frames_in_batch helps the training process stable

Thanks. Do I need to set 'accum_grad' larger than 1? Or what is the preferred value for accum_grad when 64 V100 are used?

**Comment by aluminumbox** [comment]
> > set max_frames_in_batch according to your gpu memory, bigger max_frames_in_batch helps the training process stable
> 
> Thanks. Do I need to set 'accum_grad' larger than 1? Or what is the preferred value for accum_grad when 64 V100 are used?

well accum_grad larger also makes training more stable. but you have 64 v100, I think accum_grad is not so important
