### ISSUE TITLE
Uneven dataset loaded to GPUs can cause ranks failed especially in the DDP mode.

### ISSUE THREAD

**Issue by huskyachao** [FunAudioLLM/CosyVoice#297]
**Describe the bug**
**BUG:** The uneven distribution of the dataset to GPUs can cause the error `[../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting xxxx ms for recv operation to complete`. 

**Potential root cause:** After a lot of hard work, I finally found one of the cause of the above error during multi-GPU training (also mentioned by [issue#180](https://github.com/FunAudioLLM/CosyVoice/issues/180#issue-2421715550) The root cause is that if your self-defined dataset(Iterable) distributes different number of training samples to GPUs respectively, there is a high probability that one of the GPUs finished the training first on its own distributed data. Then it has no data to load as other GPUs in the next batch (an potential phonomena I observed is that the finished GPU has a 100% GPU-Utility), which can cause the above error. 

**Potential solution:** To avoid/mitigate the above problem, be causious of the distributed subsets to each GPU. E.g., I choose to force each distributed subsets has the same number of training samples and used the `static` batch mode. By the way, it seemed that the `dynamic` batch can not guarrentee the even distribution across diffirerent GPUs (even if every subsets has the same number of samples). Because the audio/token length can be different. 

Unfortunately, I did not find a better solution for me to mitigate the above problem. Welcome to discuss more elegant solutions to the data distribution in the DDP mode.

**Comment by aluminumbox** [comment]
set partition=False in training. also please provide the whole log. it should start next epoch training though ddp timeout.

**Comment by RoversCode** [comment]
I encountered the same issue. Whenever using dynamic batching, after a certain number of steps, the error 'failed to pass monitoredBarrier' appears. At first, I thought there was a bug in the data processing pipeline, but there wasn't. Then, I suspected that the discrepancy in the amount of data each worker received was the cause, so I made sure every worker received the same amount of data, but it still didn't solve the problem. If anyone has experienced this and found a solution, I would greatly appreciate a response. Although static batching works, my device is a 4090 with limited VRAM, so dynamic batching is more suitable for me.

**Comment by stg1205** [comment]
> I encountered the same issue. Whenever using dynamic batching, after a certain number of steps, the error 'failed to pass monitoredBarrier' appears. At first, I thought there was a bug in the data processing pipeline, but there wasn't. Then, I suspected that the discrepancy in the amount of data each worker received was the cause, so I made sure every worker received the same amount of data, but it still didn't solve the problem. If anyone has experienced this and found a solution, I would greatly appreciate a response. Although static batching works, my device is a 4090 with limited VRAM, so dynamic batching is more suitable for me.

I believe when using dynamic batch, if your data have various lengths, some processes may not be left any data to load while some other processes have. So DDP get stucked.

**Comment by blackbird-fish** [comment]
Has this porblem solved? I met the same issue.
