### ISSUE TITLE
modelscope 在线demo的两个bug

### ISSUE THREAD

**Issue by yuyun2000** [FunAudioLLM/CosyVoice#3]
https://www.modelscope.cn/studios/iic/CosyVoice-300M

1、输入[laughter]属性控制时，男声都会变成女生

2、点击日本男，输入日语的时候，会提示不符合网站要求不能进行推理，韩语也是

**Comment by yuyun2000** [comment]
另外声音克隆可以增加上传文件接口吗，直接录制有两个问题，一个不方便；一个电脑麦克风垃圾，质量不好

**Comment by ZhihaoDU** [comment]
我们后续会跟进，有条件的话可以部署在本地体验

**Comment by redstoneleo** [comment]
谢谢大神！我也希望可以有上传音频文件克隆声音的功能，比如说我看到动画片里的某个角色的声音我比较喜欢，我就截取一段声音上传克隆——这就是我想要的
