### ISSUE TITLE
中文 省略号 bug

### ISSUE THREAD

**Issue by AssassinQuin** [FunAudioLLM/CosyVoice#30]
例子：
“少爷你听话，你不能出去，让小楚去，让他去吧……”

此句子中没有         pounc = ['。', '？', '！', '；', '：', '.', '?', '!', ';'] 标点符号，会导致没有字符输出，合成会失败

code：cosyvoice/utils/frontend_utils.py
    if lang == "zh":
        pounc = ['。', '？', '！', '；', '：', '.', '?', '!', ';']
    else:
        pounc = ['.', '?', '!', ';', ':']
    if comma_split:
        pounc.extend(['，', ','])
    st = 0
    utts = []
    for i, c in enumerate(text):
        if c in pounc:
            if len(text[st: i]) > 0:
                utts.append(text[st: i] + c)
            if i + 1 < len(text) and text[i + 1] in ['"', '”']:
                tmp = utts.pop(-1)
                utts.append(tmp + text[i + 1])
                st = i + 2
            else:
                st = i + 1

**Comment by aluminumbox** [comment]
This is due to text frontend error. Please modify it by yourself because we cannot consider all such cases in the code.
