### ISSUE TITLE
为什么flow的infer中feat_len = (token_len / 50 * 24000 / 256).int() 是这样计算的呢

### ISSUE THREAD

**Issue by inconnu11** [FunAudioLLM/CosyVoice#306]
如题，在https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow.py#L121 中，为什么mel的长度是token长度的一个倍数呢，不应该预测出来吗

**Comment by tyanz** [comment]
> 如题，在https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow.py#L121 中，为什么mel的长度是token长度的一个倍数呢，不应该预测出来吗

token的长度是预测的，mel的长度可以根据token长度算出来

**Comment by inconnu11** [comment]
> > 如题，在https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow.py#L121 中，为什么mel的长度是token长度的一个倍数呢，不应该预测出来吗
> 
> token的长度是预测的，mel的长度可以根据token长度算出来

但是训练的时候token和mel长度不一定是这个数量关系吧，训练时mel长度应该是从真实的mel获得的吧

**Comment by tyanz** [comment]
训练的时候token和mel都是从真实音频来的，只不过一个是经过speech_tokenizer，一个是计算mel谱

**Comment by inconnu11** [comment]
https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/flow/flow.py#L128 这里是假设要合成speech的mel长度一定大于prompt的mel长度吗

**Comment by JohnHerry** [comment]
可以用其它采样率的梅尔谱数据来训练吗？比如16K的？
