### ISSUE TITLE
报错信息：pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha'

### ISSUE THREAD

**Issue by yufengzhixing** [FunAudioLLM/CosyVoice#311]
系统：MacOS-12.6.2
运行过程中报错信息如下：
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha'

是PYTHONPATH环境变量引入错误么？
通过命令echo $PYTHONPATH查看，third_party/Matcha-TTS已加入环境变量，为什么还是报错。。。

**Comment by LAM-0706** [comment]
同样的问题 File "/opt/miniconda3/envs/cosyvoice/lib/python3.8/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha'

**Comment by yufengzhixing** [comment]
自问自答一波，我没有按说明文档安装，python改成3.9版本，然后直接安装matcha-tts，其他与文档一致，成功了

**Comment by NorthhhFishSoup** [comment]
你是不是没从git下载，你检查一下third_party下面的Matcha-TTS是不是空的
