### ISSUE TITLE
AssertionError: failed to initialize ttsfrd resource

### ISSUE THREAD

**Issue by abiglizi** [FunAudioLLM/CosyVoice#32]
运行python3 webui.py --port 50000 --model_dir iic/CosyVoice-300M时出错

**Comment by aluminumbox** [comment]
check faq.md, clone iic/CosyVoice_ttsfrd again if necessary

**Comment by abiglizi** [comment]
> check faq.md, clone iic/CosyVoice_ttsfrd again if necessary
请问，根据报错信息
File "/home/ccl-1/Documents/CosyVoice/cosyvoice/cli/frontend.py", line 53, in __init__
    assert self.frd.initialize('{}/../../pretrained_models/speech_kantts_ttsfrd/resource'.format(ROOT_DIR)) is True, 'failed to initialize ttsfrd resource'
将_'{}/../../pretrained_models/**speech_kantts_ttsfrd**/resource'_修改为_'{}/../../pretrained_models/**CosyVoice-ttsfrd**/resource'_
是否合理？

最后仍然提示load leagacy transf breakmodel

**Comment by aluminumbox** [comment]
> > check faq.md, clone iic/CosyVoice_ttsfrd again if necessary
> > 请问，根据报错信息
> > File "/home/ccl-1/Documents/CosyVoice/cosyvoice/cli/frontend.py", line 53, in **init**
> > assert self.frd.initialize('{}/../../pretrained_models/speech_kantts_ttsfrd/resource'.format(ROOT_DIR)) is True, 'failed to initialize ttsfrd resource'
> > 将`'{}/../../pretrained_models/**speech_kantts_ttsfrd**/resource'`修改为`'{}/../../pretrained_models/**CosyVoice-ttsfrd**/resource'`
> > 是否合理？
> 
> 最后仍然提示load leagacy transf breakmodel

check readme, we have changed ttsfrd download link. You can change it back it you have downloaded it already.

**Comment by kexul** [comment]
Same issue here: 
```
Traceback (most recent call last):
  File "/data/tts/CosyVoice/webui.py", line 181, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/data/tts/CosyVoice/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/data/tts/CosyVoice/cosyvoice/cli/frontend.py", line 60, in __init__
    assert self.frd.initialize('{}/../../pretrained_models/CosyVoice-ttsfrd/resource'.format(ROOT_DIR)) is True, 'failed to initialize ttsfrd resource'
AssertionError: failed to initialize ttsfrd resource
```
The resource folder is presented.

**Comment by younger027** [comment]
this [link](https://www.modelscope.cn/models/iic/CosyVoice-300M) is not fix "iic/CosyVoice_ttsfrd"

**Comment by aluminumbox** [comment]
> same issue， for my python version is 3.10, so I install ttsfrd by this `pip install -U ttsfrd -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`, but failed to initialize ttsfrd resource, how to use ttsfrd in another python version instead of python3.8?

update repo, we use wetextprocessing when ttsfrd is not avaliable

**Comment by aluminumbox** [comment]
> > > same issue， for my python version is 3.10, so I install ttsfrd by this `pip install -U ttsfrd -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`, but failed to initialize ttsfrd resource, how to use ttsfrd in another python version instead of python3.8?
> > 
> > 
> > update repo, we use wetextprocessing when ttsfrd is not avaliable
> 
> while use wetextprocessing instead none before，the inference time cost more ~20%.

well there is no perfect plan for text normalization

**Comment by niunaicoke** [comment]
> > same issue， for my python version is 3.10, so I install ttsfrd by this `pip install -U ttsfrd -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`, but failed to initialize ttsfrd resource, how to use ttsfrd in another python version instead of python3.8?
> 
> update repo, we use wetextprocessing when ttsfrd is not avaliable

are you saying cloning it again? doesnt work for me, still seeing "File "/root/CosyVoice/cosyvoice/cli/frontend.py", line 63, in __init__
    assert self.frd.initialize('{}/../../pretrained_models/CosyVoice-ttsfrd/resource'.format(ROOT_DIR)) is True, 'failed to initialize ttsfrd resource'
AssertionError: failed to initialize ttsfrd resource"

**Comment by xddun** [comment]
Here's how you can solve the issue and ensure the code works without errors:

1. Make sure you have the file `pretrained_models/CosyVoice-ttsfrd`.

2. Specifically, you need to unzip the resource file and install `ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl`.

```bash
cd pretrained_models/CosyVoice-ttsfrd/
unzip resource.zip -d .
pip install ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl
```

3. You can try the following code for inference:

```python
import os
import sys
import time
import torchaudio

# Set CUDA visibility to GPU 3
os.environ["CUDA_VISIBLE_DEVICES"] = "3"

sys.path.insert(0, os.path.abspath('third_party/Matcha-TTS'))

from cosyvoice.cli.cosyvoice import CosyVoice
from cosyvoice.utils.file_utils import load_wav

# Initialize CosyVoice model
cosyvoice = CosyVoice('pretrained_models/CosyVoice-300M-SFT')

# List available speakers
print(cosyvoice.list_avaliable_spks())

# Measure inference time
time1 = time.time()
output = cosyvoice.inference_sft('你好，我是通义生成式语音大模型，请问有什么可以帮您的吗？', '中文女')
torchaudio.save('sft.wav', output['tts_speech'], 22050)
time2 = time.time()

print(f"Used time: {time2 - time1}")
```

Regarding the ONNX model, it seems slow as generating 4 seconds of speech takes 4 seconds. This may be due to the computational limitations or inefficiencies in the ONNX runtime. You might consider optimizing the model or using a more efficient runtime environment.

**Comment by KBOZAI** [comment]
> > check faq.md, clone iic/CosyVoice_ttsfrd again if necessary
> 
> 请问，根据报错信息 File "/home/ccl-1/Documents/CosyVoice/cosyvoice/cli/frontend.py", line 53, in **init** assert self.frd.initialize('{}/../../pretrained_models/speech_kantts_ttsfrd/resource'.format(ROOT_DIR)) is True, 'failed to initialize ttsfrd resource' 将`'{}/../../pretrained_models/**speech_kantts_ttsfrd**/resource'`修改为`'{}/../../pretrained_models/**CosyVoice-ttsfrd**/resource'` 是否合理？
> 
> 最后仍然提示load leagacy transf breakmodel

"This is how I solved the problem:
Rename the CosyVoice-ttsfrd folder under pretrained_models to speech_kantts_ttsfrd."

**Comment by thimoonxy** [comment]
Do you have ttsfrd on Aarch platform? I met this issue when ran on Mac M1 laptop:
```
pip install ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl
ERROR: ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.
111

**Comment by gotoolkits** [comment]
Same issue, Mac M4 laptop, How to install  ttsfrd ??

  File ".../CosyVoice2.0/app/cosyvoice/cli/frontend.py", line 27, in <module>
    import ttsfrd
ModuleNotFoundError: No module named 'ttsfrd'

**Comment by pustar** [comment]
pip3 uninstall ttsfrd
WeTextProcessing support when ttsfrd is not avaliable
