### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '***/CosyVoice-main/examples/libritts/cosyvoice/data/test-clean/parquet/utt2parquet_000000000.json'

### ISSUE THREAD

**Issue by zhaojingxin123** [FunAudioLLM/CosyVoice#33]
echo "Run inference. Please make sure utt in tts_text is in prompt_data"
怎么准备inference的文件呀？
FileNotFoundError: [Errno 2] No such file or directory: '/***/CosyVoice-main/examples/libritts/cosyvoice/data/test-clean/parquet/utt2parquet_000000000.json'
这个是什么问题

**Comment by zhaojingxin123** [comment]
这个问题是在stage 4 inference出现的

**Comment by aluminumbox** [comment]
really, have you executed stage 1-3? what do you have in data/test-clean/parquet directory?

**Comment by huskyachao** [comment]
您好，请问你解决了吗  我也遇到了同样的问题

**Comment by wukailu** [comment]
发现因为在make_parquet_file.py里面保存parquet的时候，出现 pyarrow.lib.ArrowInvalid: ('Could not convert tensor([-0.0082,  0.0214, -0.0414,  ...,  0.0094, -0.0288, -0.0231]) with type Tensor: did not recognize Python value type when inferring an Arrow data type', 'Conversion failed for column spk_embedding with type object') 导致代码并不会保存对应的文件。试了几个版本的pyarrow都不支持 Tensor，想问下是哪个版本的pandas, pyarrow, torch 能组合起来正常运行这个

**Comment by oshindow** [comment]
> 您好，请问你解决了吗 我也遇到了同样的问题

make sure stage 3 is completed
