### ISSUE TITLE
(cosyvoice) E:\CosyVoice_For_Windows-main\CosyVoice_For_Windows-main>install deepspeed from https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311 install: target 'https://github.com/S95Sedan/Deepspeed-Windows/releases/tag/v14.0%2Bpy311' is not a directory     这是怎么回事？

### ISSUE THREAD

**Issue by tingfengaiai** [FunAudioLLM/CosyVoice#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aluminumbox** [comment]
pull repo again, we have ignored deepspeed in windows because windows do not supoort deepspeed. or you can just delete deep in requirements.txt
