### ISSUE TITLE
ubuntu执行代码出现问题

### ISSUE THREAD

**Issue by zhiwanxia** [FunAudioLLM/CosyVoice#35]
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办

**Comment by zhiwanxia** [comment]
pydoc.ErrorDuringImport: problem in cosyvoice.hifigan.generator - ModuleNotFoundError: No module named 'academicodec'还会出现这个问题

**Comment by aluminumbox** [comment]
check faq.md, export pythonpath before run python

**Comment by zhiwanxia** [comment]
> check faq.md, export pythonpath before run python
export pythonpath之后会出现这个
pydoc.ErrorDuringImport: problem in cosyvoice.hifigan.generator - ModuleNotFoundError: No module named 'academicodec'怎么办？

**Comment by Hwangkop** [comment]
did you execute this command ```git submodule update --init --recursive```

**Comment by zhiwanxia** [comment]
> did you execute this command ? `git submodule update --init --recursive`
yes,but still don't work

**Comment by ldxbxl** [comment]
> > did you execute this command ? `git submodule update --init --recursive`
> > yes,but still don't work

我也遇到了相同的报错ModuleNotFoundError: No module named 'academicodec'，我已将matcha-tts的代码放到文件夹下面了然后就出现了这个错误

**Comment by yangcunning1** [comment]
> pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办

我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录

**Comment by yangcunning1** [comment]
> pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办

我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下

**Comment by ldxbxl** [comment]
> > pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办
> 
> 我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下

ModuleNotFoundError: No module named 'academicodec'我下载并放到third_party目录下是这样报错的

**Comment by ldxbxl** [comment]
> > pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办
> 
> 我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下

请问放到third_party目录下还需要在按照Matcha-TTS的readme安装Matcha-TTS的包吗？还有是不是需要python版本大于等于3.9

**Comment by yangcunning1** [comment]
直接放入就行，不需要安装，按照git上的安装指导，安装的python3.8



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月8日(周一) 晚上10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FunAudioLLM/CosyVoice] ubuntu执行代码出现问题 (Issue #35)




   
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办
  
我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下
  
请问放到third_party目录下还需要在按照Matcha-TTS的readme安装Matcha-TTS的包吗？还有是不是需要python版本大于等于3.9

**Comment by 13140438775** [comment]
> 直接放入就行，不需要安装，按照git上的安装指导，安装的python3.8
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月8日(周一) 晚上10:42 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [FunAudioLLM/CosyVoice] ubuntu执行代码出现问题 (Issue #35) pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package报这个错误怎么办 我是这么解决的，下载Matcha-TTS，并把Matcha-TTS放到third_party目录下 请问放到third_party目录下还需要在按照Matcha-TTS的readme安装Matcha-TTS的包吗？还有是不是需要python版本大于等于3.9 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

用python3.10不可以吗？
