### ISSUE TITLE
更新 Huggingface 权重文件

### ISSUE THREAD

**Issue by qinxuye** [FunAudioLLM/CosyVoice#355]
**Is your feature request related to a problem? Please describe.**

请更新 huggingface 权重文件，huggingface 上两个组织都没有更新。

**Comment by aluminumbox** [comment]
most users use modelscope to download model, also in our readme and code, we haven't provide huggingface download method. the funaudiollm org on huggingface is inactive, we may update it if there are more feedback that wants to use huggingface download, currently we are lacking of people to maintain it

**Comment by qinxuye** [comment]
We maintained [Xinference](https://github.com/xorbitsai/inference) which allows users to use CosyVoice. We can let user choose HF or ModelScope to download models, if HF not updated, the users may not be able to use. It's a challenge for us to maintain it.

**Comment by aluminumbox** [comment]
ok, I think the model will be stable for this month, we will update it in next week

**Comment by aluminumbox** [comment]
we have updated huggingface model repo

**Comment by qinxuye** [comment]
> we have updated huggingface model repo

Thanks.
