### ISSUE TITLE
请问如何微调，训练自己的语音模型

### ISSUE THREAD

**Issue by zergtant** [FunAudioLLM/CosyVoice#39]
oneshot的效果不稳定，我看project页面说可以支持finetuning，但是在git上没有看到有关finetuning和介绍

是否会提供相关代码或者文档？

**Comment by aluminumbox** [comment]
see example/libritts/run.sh

**Comment by zergtant** [comment]
好的，我研究下，谢谢

**Comment by chenxu126** [comment]
这个run.sh是基础训练么？
