### ISSUE TITLE
Missing information of **spk_id**

### ISSUE THREAD

**Issue by TheCutestCat** [FunAudioLLM/CosyVoice#40]
Thanks for the great work of your team, 

I had a problem when using
`output = cosyvoice.inference_instruct('在面对挑战时，他展现了非凡的<strong>勇气</strong>与<strong>智慧</strong>。', '中文男', 'Theo \'Crimson\', is a fiery, passionate rebel leader. Fights with fervor for justice, but struggles with impulsiveness.')
`
there is a **spk_id** parameter， In addition to the "中文男" in the text, can you tell me other parameters that can be used?
Thank you for your help😊

**Comment by Lixi20** [comment]
Literal['中文女', '中文男', '英文女', '英文男', '日语男', '粤语女', '韩语女'] Default: "中文女"
