### ISSUE TITLE
【bug】temperature的随机性导致流式推理前后窗的mel谱不连续

### ISSUE THREAD

**Issue by boji123** [FunAudioLLM/CosyVoice#406]
https://github.com/FunAudioLLM/CosyVoice/blob/28f13533249ab835c7146a4c77e5d5a017457ca5/cosyvoice/flow/flow_matching.py#L35C46-L35C57

temperature的随机性导致流式推理时flowmatching前后窗的mel谱不连续
在推理时设置temperature=0可以显著改善此问题

**Comment by ZhihaoDU** [comment]
temperature=0效果是正常的吗，我们训练的时候temp=1.0，如果推理时temp=0.0的话noise就全0了？能否提供一个生成的例子呢？

**Comment by boji123** [comment]
该问题本质是z和mu，对同个index的token，其数值在不同chunk不一致，固定z可以减少波动，但mu不同chunk的attention输出难以对齐

**Comment by boji123** [comment]
#410

**Comment by JohnHerry** [comment]
怎么解决的？没看懂。
