### ISSUE TITLE
About instant-feature-extraction training

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#409]
We are tring to make instant-feature-extraction training of flow model, because the feature extraction is so costly on large amount of samples.  we can make instant-feature-extraction and feature cache to replace the offline-feature extraction.   
the problem is about the pretrained S3  speech token extractor.  it is an ONNX model, we can write a dataloader function about S3 speech token extraction on CPU, but it is too slow. while using GPU onnx session  in multi-card distribution training, it will always report some kind of exceptions. When we use a global onnxruntime-gpu session in all dataloaders,  report like  
 `disk.__verify_params_across_processes(process_group, tensors, loger)   NCCL error in:  ../torch.cscr/distributed/c10d/NCCLUtils.hpp:275, invalid usage, This usually reflects invalid usage of NCCL library. Last error: Duplicate GPU dected: rank3 and rank0 both on CUDA device 34000`   
when we create a independent onnxruntime-gpu sessiion in each dataloader instance,  it will report:   
`E:onnxruntime:Default, cuda_call.cc:118  CudaCall] CUDA failure 3: initialization error; GPU=0; hostname=XXX; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc; line=422; expr=cudaSetDevice(GetDeviceId()) `   
our code about speechtoken extraction is from the cosyvoice example tools code.    
So, is there any suggestion to make stable instant-feature-extraction traning on distributed training of cosyvoide flow?

**Comment by aluminumbox** [comment]
dataloader is multiprocessing, I think onnx do not support multi-process inference using one instance
