### ISSUE TITLE
Possible to share codes to reproduce examples in demo page? 

### ISSUE THREAD

**Issue by tshmak** [FunAudioLLM/CosyVoice#421]
Thanks for open sourcing this work. The [demo page](https://fun-audio-llm.github.io/) has some really great sounding examples. However, it's unsure how I can obtain the voices of, e.g. "Assistant_大东", "Assistant_小夏", etc. 

Would it be possible to provide scripts for reproducing the examples also?

**Comment by aluminumbox** [comment]
sorry some example in demo page has privacy restriction, we cannot opensource its spk embedding
