### ISSUE TITLE
Why yield {**sample} rather than yield sample in cosyvoice/dataset/processor.py

### ISSUE THREAD

**Issue by huskyachao** [FunAudioLLM/CosyVoice#425]
https://github.com/FunAudioLLM/CosyVoice/blob/f6d44af14606fd0624d9dc8a2490d65fce02b1d9/cosyvoice/dataset/processor.py#L49-L50
Hi, I noticed that there is a note in cosyvoice/dataset/processor.py. I want to know why not `yield sample` directly but `yield {**sample}`? As far as I know, the latter will create a new dict which takes more memory. Is there any concern or bugs (e.g., memory leakge?) if just using `yield sample`?

**Comment by aluminumbox** [comment]
in inference mode, the sample dict will be used multiple time, in case we change the origin dict
