### ISSUE TITLE
About the multiprocess loading of the iterable trainset

### ISSUE THREAD

**Issue by huskyachao** [FunAudioLLM/CosyVoice#427]
Hi, I noticed that cosyvoice used an iterable dataset and support multiprocess dataloader with `num_workers>0`. 
https://github.com/FunAudioLLM/CosyVoice/blob/f6d44af14606fd0624d9dc8a2490d65fce02b1d9/cosyvoice/utils/train_utils.py#L59-L63
But it seemed that there is no proper solution about the iterable dataloading (e.g., divide the dataset and distribute each subset to each process) in `CosyVoice/cosyvoice/dataset/dataset.py` when `num_workers>0`. 
https://github.com/FunAudioLLM/CosyVoice/blob/f6d44af14606fd0624d9dc8a2490d65fce02b1d9/cosyvoice/dataset/dataset.py#L117-L123
Will this load the same data with multiple times (i.e., duplicate data)?

**Comment by aluminumbox** [comment]
no duplicate data, it will split the data according to num_workers https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/dataset/dataset.py#L94

**Comment by huskyachao** [comment]
> no duplicate data, it will split the data according to num_workers https://github.com/FunAudioLLM/CosyVoice/blob/main/cosyvoice/dataset/dataset.py#L94

OK. I see. My apologies.
