### ISSUE TITLE
ttsfrd安装起来比较麻烦，能不能换成WeTextProcessing，也是一个比较好用的TN库。

### ISSUE THREAD

**Issue by lidingke** [FunAudioLLM/CosyVoice#43]
ttsfrd安装起来比较麻烦，能不能换成WeTextProcessing，也是一个比较好用的TN库。

**Comment by aluminumbox** [comment]
we will replace it later

**Comment by aluminumbox** [comment]
update code, we have used wetextprocessing to replace ttsfrd

**Comment by sirius-ai** [comment]
while use wetextprocessing instead none before，the inference time cost more ~20%.
