### ISSUE TITLE
cosyvoice  | ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling cosyvoice  | transformer is not installed, please install it if you want to use related modules

### ISSUE THREAD

**Issue by Liyu910228** [FunAudioLLM/CosyVoice#434]
<img width="718" alt="903b710a73bae05fdb719951b01547b" src="https://github.com/user-attachments/assets/32960714-53c3-4049-89aa-6b395d628e79">
<img width="718" alt="903b710a73bae05fdb719951b01547b" src="https://github.com/user-attachments/assets/86f24ca3-4e7e-4326-9165-b74117d56e77">
transformer也已经安装了，还是一直报这个错误

**Comment by aluminumbox** [comment]
update code and model

**Comment by Liyu910228** [comment]
> update code and model

大佬给一下命令啊，更新了模型不行啊

**Comment by ScottishFold007** [comment]
我刚才更了代码也是一个样

**Comment by Liyu910228** [comment]
> 我刚才更了代码也是一个样

现在解决吗？？怎么解决啊
