### ISSUE TITLE
语音克隆时，300M 或 300HZ 对两个字的文本生成空语音

### ISSUE THREAD

**Issue by m358807551** [FunAudioLLM/CosyVoice#438]
现象：生成的语音是空的，或者说没有能识别的人声。
功能：语音克隆
输入文本：好的、收到、测试  等这些两个字的短文本
复现概率：目前看跟上传的要模仿的音频有关，差不多有50%的概率能复现

**Comment by aluminumbox** [comment]
把具体代码和prompt音频贴上来

**Comment by m358807551** [comment]
最近测试没有复现，先 close了。
