### ISSUE TITLE
Length limit of 25Hz s3tokenizer

### ISSUE THREAD

**Issue by sphmel** [FunAudioLLM/CosyVoice#439]
It seems now it downsamples mel 4x first then feeding into transformer, and transformer's pos emb limit is still 1500, which would be 60 seconds of audio.

so max length of tokenizer becomes 60s. am i right?

**Comment by aluminumbox** [comment]
yes

**Comment by Mddct** [comment]
参考这个：https://github.com/Mddct/s3tokenizer-long
