### ISSUE TITLE
模型里面的llm是否支持单字流式输入进行编码

### ISSUE THREAD

**Issue by wang-TJ-20** [FunAudioLLM/CosyVoice#441]
你好咨询下，目前模型里的llm模块是一段文本输入进行编码，然后送入flow进行音频合成，想问下是否支持流式单字输入进行编码，等单字编码的token数满足self.token_min_hop_len，然后送入flow进行音频合成

**Comment by aluminumbox** [comment]
no, we only support sentence level stream input

**Comment by Hkaisense** [comment]
我看阿里云的官网应用是支持大模型生成的单字直接输入的开源版本不支持吗？
