### ISSUE TITLE
Is the flow model trained with half-precision works well?

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#446]
In the pretained opensource stack, the llm support half inference but not flow model.  If I train the flow with deepspeed and get a half-precision float model, will it works well?  will it get good speech quality?

**Comment by aluminumbox** [comment]
not amp trained, we will update cosyvoice-300m and coysvoice-300m-25hz with amp training later

**Comment by JohnHerry** [comment]
ok， thank you for the help

**Comment by JohnHerry** [comment]
> ok， thank you for the help
 by the way,  what I mean is to train the base model from scratch. not to fine tune on the released pretraines.
