### ISSUE TITLE
The  Voice Conversion (VC) effect is not similar

### ISSUE THREAD

**Issue by wen0320** [FunAudioLLM/CosyVoice#452]
First of all, thank you very much for updating the VC function!!!
The newly released VC function was tested and found that after the timbre conversion, the generated voice sounds neither like A nor like B. And the VC function should not have been trained separately? Is it possible to optimize the effect of VC?

**Comment by aluminumbox** [comment]
please provide an example of your prompt and source speech

**Comment by wen0320** [comment]
[bad effect wavs.zip](https://github.com/user-attachments/files/17178456/bad.effect.wavs.zip)
Thank you very much for your reply. A lot of audio is the effect, and I just chose an example.
