### ISSUE TITLE
Thank you for the great app! – I have made an alternative English GUI with addons

### ISSUE THREAD

**Issue by PasiKoodaa** [FunAudioLLM/CosyVoice#464]
https://github.com/PasiKoodaa/CosyVoice-optimized

I am not a great coder, so I am not going to do a pull request.

My version have few addons, like:

- Translated GUI to English

- Uses chunking to handle input text and output audio, so it's possible to make much longer audios

- Optimized the GUI audio view (still has a "bug" that it starts playing from the start when new audio files are added in the GUI, but you can download even partial results this way)

- Stop button

- Faster-whipser for transcribing the input audio

**Comment by platform-kit** [comment]
@PasiKoodaa can you share the relevant excerpt where you implemented chunking for longform generation?
