### ISSUE TITLE
微调

### ISSUE THREAD

**Issue by suzhenghang** [FunAudioLLM/CosyVoice#5]
训练细节好像很少，如果要用自有数据微调，可以怎么做？

**Comment by ZhihaoDU** [comment]
我们在这里提供了以LibriTTS为例的微调recipe
https://github.com/FunAudioLLM/CosyVoice/tree/main/examples/libritts/cosyvoice

**Comment by plutols** [comment]
这个是以英文微调为例，还是只支持英文的微调呢

**Comment by yubinyes** [comment]
请问按照这个脚本训练出来的模型，就可以支持tts和voice clone吗？跨语言inference_cross_lingual的话，中英数据集都需要吗？

**Comment by aluminumbox** [comment]
> 请问按照这个脚本训练出来的模型，就可以支持tts和voice clone吗？跨语言inference_cross_lingual的话，中英数据集都需要吗？

yes, it can, and you need both english and chinese data for cross_lingual inference
