### ISSUE TITLE
torch2.4.1没有mac intel处理器版本，有没有替代方案？

### ISSUE THREAD

**Issue by benojan** [FunAudioLLM/CosyVoice#501]
<img width="533" alt="iShot_2024-10-13_20 52 51" src="https://github.com/user-attachments/assets/52a09ad0-9320-4955-b562-600c17844f6f">

mac系统intel架构的，pip仓库没有torch==2.4.1怎么办？

_Originally posted by @benojan in https://github.com/FunAudioLLM/CosyVoice/issues/445#issuecomment-2408969736_

**Comment by aluminumbox** [comment]
我们的requirements是2.0.1
