### ISSUE TITLE
cosyvoice/tokenizer/assets/multilingual_zh_ja_yue_char_del.tiktoken 这个文件长度和cosyvoice.yaml 中text token 长度不一致

### ISSUE THREAD

**Issue by Wentao795** [FunAudioLLM/CosyVoice#510]
hi，感谢大佬的工作。

请问，multilingual_zh_ja_yue_char_del.tiktokentoken 长度 和 cosyvoice.yaml 中text token 不一致会对结果有影响吗？
![image](https://github.com/user-attachments/assets/fb122b20-badb-43e4-9911-4103633e5c7f)
![image](https://github.com/user-attachments/assets/927b4e7a-59c3-4fbb-afca-56cbdabcb706)

**Comment by aluminumbox** [comment]
不是一致的，multilingual_zh_ja_yue_char_del.tiktokentoken跟25hz的配置一起使用就可以
