### ISSUE TITLE
Zero Shot Inference Error

### ISSUE THREAD

**Issue by sekkit** [FunAudioLLM/CosyVoice#52]
when do zero_shot_inference, i uploaded a chinese mp3, it throws:
When I trim the audio length to shorter, the error is gone. 
2024-07-08 17:52:16,887 DEBUG Used_phis: defaultdict(<class 'set'>,
            {State(pc_initial=0 nstack_initial=0): set(),
             State(pc_initial=186 nstack_initial=0): set(),
             State(pc_initial=190 nstack_initial=0): set()})
2024-07-08 17:52:16,888 DEBUG defmap: {}
2024-07-08 17:52:16,888 DEBUG phismap: defaultdict(<class 'set'>, {})
2024-07-08 17:52:16,888 DEBUG changing phismap: defaultdict(<class 'set'>, {})
2024-07-08 17:52:16,888 DEBUG keep phismap: {}
2024-07-08 17:52:16,888 DEBUG new_out: defaultdict(<class 'dict'>, {})
2024-07-08 17:52:16,888 DEBUG ----------------------DONE Prune PHIs-----------------------
2024-07-08 17:52:16,888 DEBUG block_infos State(pc_initial=0 nstack_initial=0):
AdaptBlockInfo(insts=((0, {}), (2, {}), (4, {'res': '$x4.0'}), (6, {'res': '$const6.1'}), (8, {'index': '$const6.1', 'target': '$x4.0', 'res': '$8binary_subscr.2'}), (10, {}), (12, {}), (14, {}), (16, {}), (18, {'res': '$x18.3'}), (20, {'res': '$const20.4'}), (22, {'index': '$const20.4', 'target': '$x18.3', 'res': '$22binary_subscr.5'}), (24, {}), (26, {}), (28, {}), (30, {}), (32, {'op': '+', 'lhs': '$8binary_subscr.2', 'rhs': '$22binary_subscr.5', 'res': '$binop_add32.6'}), (34, {}), (36, {'res': '$const36.7'}), (38, {'res': '$x38.8'}), (40, {'res': '$const40.9'}), (42, {'index': '$const40.9', 'target': '$x38.8', 'res': '$42binary_subscr.10'}), (44, {}), (46, {}), (48, {}), (50, {}), (52, {'op': '*', 'lhs': '$const36.7', 'rhs': '$42binary_subscr.10', 'res': '$binop_mul52.11'}), (54, {}), (56, {'op': '-', 'lhs': '$binop_add32.6', 'rhs': '$binop_mul52.11', 'res': '$binop_sub56.12'}), (58, {}), (60, {'value': '$binop_sub56.12'}), (62, {'res': '$x62.13'}), (64, {'res': '$const64.14'}), (66, {'index': '$const64.14', 'target': '$x62.13', 'res': '$66binary_subscr.15'}), (68, {}), (70, {}), (72, {}), (74, {}), (76, {'res': '$x76.16'}), (78, {'res': '$const78.17'}), (80, {'index': '$const78.17', 'target': '$x76.16', 'res': '$80binary_subscr.18'}), (82, {}), (84, {}), (86, {}), (88, {}), (90, {'op': '-', 'lhs': '$66binary_subscr.15', 'rhs': '$80binary_subscr.18', 'res': '$binop_sub90.19'}), (92, {}), (94, {'res': '$const94.20'}), (96, {'op': '/', 'lhs': '$binop_sub90.19', 'rhs': '$const94.20', 'res': '$binop_truediv96.21'}), (98, {}), (100, {'value': '$binop_truediv96.21'}), (102, {'idx': 0, 'res': '$102load_global.22'}), (104, {}), (106, {}), (108, {}), (110, {}), (112, {}), (114, {'item': '$102load_global.22', 'res': '$114load_attr.24'}), (116, {}), (118, {}), (120, {}), (122, {}), (124, {'res': '$b124.25'}), (126, {}), (128, {}), (130, {'func': '$114load_attr.24', 'args': ['$b124.25'], 'kw_names': None, 'res': '$130call.26'}), (132, {}), (134, {}), (136, {}), (138, {}), (140, {'idx': 0, 'res': '$140load_global.27'}), (142, {}), (144, {}), (146, {}), (148, {}), (150, {}), (152, {'item': '$140load_global.27', 'res': '$152load_attr.29'}), (154, {}), (156, {}), (158, {}), (160, {}), (162, {'res': '$a162.30'}), (164, {}), (166, {}), (168, {'func': '$152load_attr.29', 'args': ['$a162.30'], 'kw_names': None, 'res': '$168call.31'}), (170, {}), (172, {}), (174, {}), (176, {}), (178, {'lhs': '$130call.26', 'rhs': '$168call.31', 'res': '$178compare_op.32'}), (180, {}), (182, {}), (184, {'pred': '$178compare_op.32'})), outgoing_phis={}, blockstack=(), active_try_block=None, outgoing_edgepushed={186: (), 190: ()})
2024-07-08 17:52:16,889 DEBUG block_infos State(pc_initial=186 nstack_initial=0):
AdaptBlockInfo(insts=((186, {'res': '$const186.0'}), (188, {'retval': '$const186.0', 'castval': '$188return_value.1'})), outgoing_phis={}, blockstack=(), active_try_block=None, outgoing_edgepushed={})
2024-07-08 17:52:16,889 DEBUG block_infos State(pc_initial=190 nstack_initial=0):
AdaptBlockInfo(insts=((190, {'res': '$b190.0'}), (192, {'value': '$b190.0', 'res': '$192unary_negative.1'}), (194, {'res': '$a194.2'}), (196, {'op': '/', 'lhs': '$192unary_negative.1', 'rhs': '$a194.2', 'res': '$binop_truediv196.3'}), (198, {}), (200, {'retval': '$binop_truediv196.3', 'castval': '$200return_value.4'})), outgoing_phis={}, blockstack=(), active_try_block=None, outgoing_edgepushed={})
2024-07-08 17:52:16,890 DEBUG label 0:
    x = arg(0, name=x)                       ['x']
    $const6.1 = const(int, 1)                ['$const6.1']
    $8binary_subscr.2 = getitem(value=x, index=$const6.1, fn=<built-in function getitem>) ['$8binary_subscr.2', '$const6.1', 'x']
    $const20.4 = const(int, -1)              ['$const20.4']
    $22binary_subscr.5 = getitem(value=x, index=$const20.4, fn=<built-in function getitem>) ['$22binary_subscr.5', '$const20.4', 'x']
    $binop_add32.6 = $8binary_subscr.2 + $22binary_subscr.5 ['$22binary_subscr.5', '$8binary_subscr.2', '$binop_add32.6']
    $const36.7 = const(int, 2)               ['$const36.7']
    $const40.9 = const(int, 0)               ['$const40.9']
    $42binary_subscr.10 = getitem(value=x, index=$const40.9, fn=<built-in function getitem>) ['$42binary_subscr.10', '$const40.9', 'x']
    $binop_mul52.11 = $const36.7 * $42binary_subscr.10 ['$42binary_subscr.10', '$binop_mul52.11', '$const36.7']
    a = $binop_add32.6 - $binop_mul52.11     ['$binop_add32.6', '$binop_mul52.11', 'a']
    $const64.14 = const(int, 1)              ['$const64.14']
    $66binary_subscr.15 = getitem(value=x, index=$const64.14, fn=<built-in function getitem>) ['$66binary_subscr.15', '$const64.14', 'x']
    $const78.17 = const(int, -1)             ['$const78.17']
    $80binary_subscr.18 = getitem(value=x, index=$const78.17, fn=<built-in function getitem>) ['$80binary_subscr.18', '$const78.17', 'x']
    $binop_sub90.19 = $66binary_subscr.15 - $80binary_subscr.18 ['$66binary_subscr.15', '$80binary_subscr.18', '$binop_sub90.19']
    $const94.20 = const(int, 2)              ['$const94.20']
    b = $binop_sub90.19 / $const94.20        ['$binop_sub90.19', '$const94.20', 'b']
    $102load_global.22 = global(np: <module 'numpy' from 'C:\\Users\\sekkitshi\\AppData\\Local\\miniconda3\\envs\\cosyvoice\\Lib\\site-packages\\numpy\\__init__.py'>) ['$102load_global.22']
    $114load_attr.24 = getattr(value=$102load_global.22, attr=abs) ['$102load_global.22', '$114load_attr.24']
    $130call.26 = call $114load_attr.24(b, func=$114load_attr.24, args=[Var(b, pitch.py:429)], kws=(), vararg=None, varkwarg=None, target=None) ['$114load_attr.24', '$130call.26', 'b']
    $140load_global.27 = global(np: <module 'numpy' from 'C:\\Users\\sekkitshi\\AppData\\Local\\miniconda3\\envs\\cosyvoice\\Lib\\site-packages\\numpy\\__init__.py'>) ['$140load_global.27']
    $152load_attr.29 = getattr(value=$140load_global.27, attr=abs) ['$140load_global.27', '$152load_attr.29']
    $168call.31 = call $152load_attr.29(a, func=$152load_attr.29, args=[Var(a, pitch.py:428)], kws=(), vararg=None, varkwarg=None, target=None) ['$152load_attr.29', '$168call.31', 'a']
    $178compare_op.32 = $130call.26 >= $168call.31 ['$130call.26', '$168call.31', '$178compare_op.32']
    bool184 = global(bool: <class 'bool'>)   ['bool184']
    $184pred = call bool184($178compare_op.32, func=bool184, args=(Var($178compare_op.32, pitch.py:431),), kws=(), vararg=None, varkwarg=None, target=None) ['$178compare_op.32', '$184pred', 'bool184']
    branch $184pred, 186, 190                ['$184pred']
label 186:
    $const186.0 = const(int, 0)              ['$const186.0']
    $188return_value.1 = cast(value=$const186.0) ['$188return_value.1', '$const186.0']
    return $188return_value.1                ['$188return_value.1']
label 190:
    $192unary_negative.1 = unary(fn=<built-in function neg>, value=b) ['$192unary_negative.1', 'b']
    $binop_truediv196.3 = $192unary_negative.1 / a ['$192unary_negative.1', '$binop_truediv196.3', 'a']
    $200return_value.4 = cast(value=$binop_truediv196.3) ['$200return_value.4', '$binop_truediv196.3']
    return $200return_value.4                ['$200return_value.4']

2024-07-08 17:52:17.2848084 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:560 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 1500 by 1932

Traceback (most recent call last):
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "X:\tmp\CosyVoice_For_Windows-pack\webui.py", line 126, in generate_audio
    output = cosyvoice.inference_zero_shot(tts_text, prompt_text, prompt_speech_16k)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\tmp\CosyVoice_For_Windows-pack\cosyvoice\cli\cosyvoice.py", line 63, in inference_zero_shot
    model_input = self.frontend.frontend_zero_shot(i, prompt_text, prompt_speech_16k)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\tmp\CosyVoice_For_Windows-pack\cosyvoice\cli\frontend.py", line 120, in frontend_zero_shot
    speech_token, speech_token_len = self._extract_speech_token(prompt_speech_16k)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\tmp\CosyVoice_For_Windows-pack\cosyvoice\cli\frontend.py", line 66, in _extract_speech_token
    speech_token = self.speech_tokenizer_session.run(None, {self.speech_tokenizer_session.get_inputs()[0].name: feat.detach().cpu().numpy(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekkitshi\AppData\Local\miniconda3\envs\cosyvoice\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:560 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 1500 by 1932

**Comment by aluminumbox** [comment]
make sure prompt audio less than 30s
