### ISSUE TITLE
Windows+WSL部署极速复刻模式生成后显存并未释放以及中长文本显存占用问题

### ISSUE THREAD

**Issue by hotdogarea** [FunAudioLLM/CosyVoice#54]
文字长度大概在140个字，一次生成，显存占用15.7G
并且在音频生成后显存并未释放，再次生成直接爆显存了
![微信截图_20240708183855](https://github.com/FunAudioLLM/CosyVoice/assets/11146882/d07d2152-0c18-4938-ac41-7981bdb87e6a)

此时控制台消息：
/root/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/gradio/processing_utils.py:582: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))

**Comment by yuanmaitian** [comment]
是的，我用Ubuntu也是，占用的显存一直没有释放，大概有20G显存一直没有释放。不知要如何修改？

**Comment by aluminumbox** [comment]
update code, we add torch.cuda.empty_cache to release cuda memory
