### ISSUE TITLE
Zero shot/cross lingual generation with speech prompt more than 30s will raise ONNXRuntimeError

### ISSUE THREAD

**Issue by gfl699468** [FunAudioLLM/CosyVoice#55]
**Describe the bug**
Zero shot/cross lingual generation with speech prompt more than 30s will raise ONNXRuntimeError 
`[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Add node. Name:'/Add_2' Status Message: [/Add_2](https://vscode-remote+ssh-002dremote-002bpublic-005fdev-005f4090.vscode-resource.vscode-cdn.net/Add_2): right operand cannot broadcast on dim 0 LeftShape: {1,1671,1280}, RightShape: {1500,1280}` at 
https://github.com/FunAudioLLM/CosyVoice/blob/4e43a9d98b9792d050a281951295f06bc7ef13e2/cosyvoice/cli/frontend.py#L73

**Expected behavior**
should raise explicit exception or trim speech prompt(for cross lingual)

**Comment by aluminumbox** [comment]
@gfl699468 we will be happy if you can create an PR to gr.error when prompt audio longer than 30s in zero shot mode, and truncate it to 30s in cross lingual mode

**Comment by aluminumbox** [comment]
> Hey, guys. Does anyone know why this error occurs when the length of prompt audio is longer than 30s?

check report, position embedding in speech tokenizer max 30s
