### ISSUE TITLE
“啊啊啊啊” 发音发不出来

### ISSUE THREAD

**Issue by liuhuang31** [FunAudioLLM/CosyVoice#594]
文本中有“啊”话，“啊”字发音发不出来，但少了口字旁的“阿”就没问题。

**Comment by aluminumbox** [comment]
把具体代码以及Prompt音频贴上来

**Comment by liuhuang31** [comment]
> 把具体代码以及Prompt音频贴上来

前端问题，wenetprocess会把“啊”字抹掉，换成ttsfrd就行了，谢谢回复～
