### ISSUE TITLE
how does llm model prosody?

### ISSUE THREAD

**Issue by yangyazhou97** [FunAudioLLM/CosyVoice#601]
Which of the LLM inputs, speech_token or embedding, contains prosody information? Isn’t the speech_feat input for flow_matching supposed to carry prosody information? Does the LLM only focus on reconstructing semantic content, while flow_matching handles the reconstruction of prosody and timbre?

**Comment by aluminumbox** [comment]
llm focus on semantic and prosody, llm also influence timbre, flow matching focus on timbre and audio quality

**Comment by yangyazhou97** [comment]
Thanks a lot
