### ISSUE TITLE
LOAD WAV AUTO CUTTER

### ISSUE THREAD

**Issue by osmankrblt** [FunAudioLLM/CosyVoice#606]
```
def load_wav(wav, target_sr):
    speech, sample_rate = torchaudio.load(wav)
    speech = speech.mean(dim=0, keepdim=True)
    
 
    if sample_rate != target_sr:
        assert sample_rate > target_sr, f'wav sample rate {sample_rate} must be greater than {target_sr}'
        speech = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sr)(speech)
    
    
    max_length = target_sr * 30  
    if speech.size(1) > max_length:
        speech = speech[:, :max_length]
    
    return speech
```

Hello! When audio files exceed 30 seconds, they trigger an error. Automatically trimming any excess beyond 30 seconds would simplify the process. Instead of performing operations on the audio, saving it, and then changing the path name (which is time-consuming), this approach would be more efficient.

**Comment by aluminumbox** [comment]
we want the user to process the audio, simply truncate it may lead to undesired result, for example prompt wav and audio mismatch

**Comment by osmankrblt** [comment]
Thank you for answer.
