### ISSUE TITLE
finetune 训练卡死

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#627]
正在finetune一个flow模块， 用6卡环境做的， 训练数据分到 156个不同的 块加载文件，每个文件包含的样本数小于等于1000个。
训练到第一个epoch结束的时候，在 executor.py :47
```
with model_context():
   .... 执行完毕
   这里卡死 hang住
```    
整个训练流程堵死了。 请问这种情况怎么处理呢？ 是否是 两个步骤forward对应一个backword的设置【accum_grad=2】，如果卡上的batch数不是2的整数倍，就会引发这种现象呢？

**Comment by aluminumbox** [comment]
数据极端的不均衡会导致卡死，可以试试train_dataset里设置partition=False试试，代码应该不需要修改

**Comment by JohnHerry** [comment]
> 数据极端的不均衡会导致卡死，可以试试train_dataset里设置partition=False试试，代码应该不需要修改

感谢，下修了训练的 prefetch 参数和timeout参数，现在可以正常运行了。 prefetch 100-> 1,   timeout 6000 -> 60
