### ISSUE TITLE
微调时，训练 loss 不断降低，评估 loss 不断升高？

### ISSUE THREAD

**Issue by zhusy09** [FunAudioLLM/CosyVoice#63]
按照 libritts 训练几个中文说话人的模型，结果发现训练 loss 不断降低，但是评估 loss 在不断升高，但是推理时合成的音频又都正常，这是什么原因？
第二个问题，例子里写的是微调 200 轮，那实际上 10 小时以内的数据规模，大概需要多少轮？

**Comment by ScottishFold007** [comment]
> 按照 libritts 训练几个中文说话人的模型，结果发现训练 loss 不断降低，但是评估 loss 在不断升高，但是推理时合成的音频又都正常，这是什么原因？ 第二个问题，例子里写的是微调 200 轮，那实际上 10 小时以内的数据规模，大概需要多少轮？
典型的过拟合现象，数据搞多些吧

**Comment by jiangxiaobai222** [comment]
> 按照 libritts 训练几个中文说话人的模型，结果发现训练 loss 不断降低，但是评估 loss 在不断升高，但是推理时合成的音频又都正常，这是什么原因？ 第二个问题，例子里写的是微调 200 轮，那实际上 10 小时以内的数据规模，大概需要多少轮？

感觉是过拟合了，也许轮数少一些会好。

同时您提到的“例子里写的是微调200轮”，请问这个例子指什么，麻烦了

**Comment by zhusy09** [comment]
对，就是这个。

**Comment by KevinWang676** [comment]
@zhusy09 可以一起交流一下微调过程吗，我的微信是Kevin985676

**Comment by AssassinQuin** [comment]
能不能写个简单的微调流程呢？我卡在配置文件那，不知道应该怎么填写，万分感谢🙏

**Comment by zhusy09** [comment]
目前参照 fish speech 项目，把 学习率降低了，epoch 也降低了，总算正常了。

**Comment by AssassinQuin** [comment]
> 目前参照 fish speech 项目，把 学习率降低了，epoch 也降低了，总算正常了。

请问你数据规模多大？参数怎么调的呢？

**Comment by AssassinQuin** [comment]
好的谢谢🙏

**Comment by sunnnnnnnny** [comment]
对于微调的数据量要求是多少呢？用10几分钟的数据去微调，效果没什么提升
