### ISSUE TITLE
在windows环境下启动时，遇到RuntimeError: torchaudio.utils.sox_utils.set_buffer_size requires sox extension, but TorchAudio is not compiled with it. Please build TorchAudio with libsox support.问题

### ISSUE THREAD

**Issue by Downupanddownup** [FunAudioLLM/CosyVoice#65]
windows的python环境下，启动项目时，遇到RuntimeError: torchaudio.utils.sox_utils.set_buffer_size requires sox extension, but TorchAudio is not compiled with it. Please build TorchAudio with libsox support.这个问题，有什么好的解决方法吗？还是说，必须得在docker中部署？
![image](https://github.com/FunAudioLLM/CosyVoice/assets/12596230/85e5ec75-0700-4cba-8968-8aeafbca443c)

**Comment by Downupanddownup** [comment]
![image](https://github.com/FunAudioLLM/CosyVoice/assets/12596230/b7a66b21-c094-46de-8030-f3343497bfbc)
把这段代码注释掉

**Comment by aluminumbox** [comment]
try pip install soxr, we do not have windows environment, you may try this and tell us whether it works

**Comment by Downupanddownup** [comment]
> try pip install soxr, we do not have windows environment, you may try this and tell us whether it works
No, it does not work.
![U~ZWUTSF_ B1(MO`84P 7}C](https://github.com/FunAudioLLM/CosyVoice/assets/12596230/20f9fca2-f220-445c-a3e0-088745603d11)

**Comment by aluminumbox** [comment]
we removed torchaudio.utils.sox_utils.set_buffer_size(16500) as sox is not need yet, you should be able to run it on windows not
