### ISSUE TITLE
windows run success

### ISSUE THREAD

**Issue by cacard** [FunAudioLLM/CosyVoice#66]
if whisper error, reinstall:
pip install git+https://github.com/openai/whisper.git

hydra install:
pip install hydra-core --upgrade

SoX error, just comment out this line:
cosyvoice/dataset/processor.py
torchaudio.utils.sox_utils.set_buffer_size(16500)

run ok.

**Comment by aluminumbox** [comment]
try pip install soxr

**Comment by cacard** [comment]
> try pip install soxr

install success, but get the same error.

**Comment by aluminumbox** [comment]
we removed torchaudio.utils.sox_utils.set_buffer_size(16500) as sox is not need yet
