### ISSUE TITLE
运行python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M报错

### ISSUE THREAD

**Issue by abiglizi** [FunAudioLLM/CosyVoice#68]
(cosyvoice) ccl-1@ubuntu:~/Documents/CosyVoice$ python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M
2024-07-08 21:08:06,929 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-07-08 21:08:06,930 - modelscope - INFO - Loading ast index from /home/ccl-1/.cache/modelscope/ast_indexer
2024-07-08 21:08:06,930 - modelscope - INFO - No valid ast index found from /home/ccl-1/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2024-07-08 21:08:07,063 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 c08faed2f2293c09201085508f34fdcb and a total number of 980 components indexed
transformer is not installed, please install it if you want to use related modules
/home/ccl-1/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/home/ccl-1/miniconda3/envs/cosyvoice/lib/python3.8/site-packages/diffusers/models/lora.py:393: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
2024-07-08 21:08:17,720 INFO input frame rate=50
load leagacy transf breakmodel
load leagacy transf breakmodel
text.cc: festival_Text_init
open voice lang map failed
break model index not valid
Killed

尝试过删除.cache/modelscope/ast_indexer仍然报错
因为提升transformer is not installed, please install it if you want to use related modules，所以是否需要安装呢
是否是load leagacy transf breakmodel导致的，能够重置model呢

**Comment by aluminumbox** [comment]
looks like you do not have enough memory

**Comment by aluminumbox** [comment]
update the code and install requirements, we have used wetextprocessing to replace ttsfrd

**Comment by neuxys** [comment]
> update the code and install requirements, we have used wetextprocessing to replace ttsfrd

Should use_ttsfrd be set to False by default in frontend.py?

**Comment by ucasiggcas** [comment]
have the similar bug,
```
load leagacy transf breakmodel
load leagacy transf breakmodel
festival_initialize() called more than once
open voice lang map failed
break model index not valid
```
then the mic can't be used

**Comment by ucasiggcas** [comment]
![QQ_1722829837049](https://github.com/user-attachments/assets/c0fe4e83-61e4-455e-a530-563b74def79a)
