### ISSUE TITLE
Win11 按文档安装启动webUI无任何反应 直接跳出了

### ISSUE THREAD

**Issue by iloveuaa** [FunAudioLLM/CosyVoice#689]
1、下载zip 解压，然后安装
2、执行
```
conda create -n cosyvoice python=3.8
conda activate cosyvoice
# pynini is required by WeTextProcessing, use conda to install it as it can be executed on all platform.
conda install -y -c conda-forge pynini==2.1.5
pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com
```
3、下载模型
4、启动，然后如图所示
![image](https://github.com/user-attachments/assets/8f97f78b-58f3-42cf-b610-565571d7e341)

**Comment by aluminumbox** [comment]
没有日志，不清楚原因

**Comment by iloveuaa** [comment]
> 没有日志，不清楚原因

日志默认在哪个文件可以看，我这边什么提示都没有就退出了

**Comment by SPRCSY** [comment]
windows下python3命令是没有反应的，需要在cosyvoice的env激活时调用python命令，或者未激活cosyvoice环境时指定路径调用cosyvoice的env文件夹里面的那个python或者pythonw来跑

**Comment by iloveuaa** [comment]
> windows下python3命令是没有反应的，需要在cosyvoice的env激活时调用python命令，或者未激活cosyvoice环境时指定路径调用cosyvoice的env文件夹里面的那个python或者pythonw来跑

激活了，是在cosyvoice环境下的，截图上有的。我win上没有python3的，日志也没有输出，找不到原因了

**Comment by h932038827** [comment]
![err](https://github.com/user-attachments/assets/9ee5051d-b1c9-4208-b012-f379bcc20879)
win11，遇到了相同问题

**Comment by heartInsert** [comment]
@h932038827 解决了吗
