### ISSUE TITLE
如何开启LOG日志，启动无反应

### ISSUE THREAD

**Issue by iloveuaa** [FunAudioLLM/CosyVoice#690]
如何开启LOG日志，启动无反应，也不报错，也无任何信息输出， 搜索文件也未看到log文件。

求大佬指导，感谢！

**Comment by aluminumbox** [comment]
terminal里应该有日志

**Comment by iloveuaa** [comment]
> terminal里应该有日志

然而是没有的，不知道怎么搞了。
5600x 4060TI 16G
