### ISSUE TITLE
多个请求的时候gpu利用率100%卡死

### ISSUE THREAD

**Issue by xuejiale929** [FunAudioLLM/CosyVoice#706]
大佬好，ubuntu20.04  4090,按照文档部署后，写了个demo，同时请求超过5个后，出现gpu利用率100%，卡死不释放，服务也假死了，日志有打印：
/root/miniconda3/envs/cv/lib/python3.8/site-packages/torch/nn/modules/module.py:1501: UserWarning: operator() sees varying value in profiling, ignoring and this should be handled by GUARD logic (Triggered internally at ../third_party/nvfuser/csrc/parser.cpp:3777.)                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
  return forward_call(*args, **kwargs)

**Comment by xuejiale929** [comment]
补充：/root/miniconda3/envs/cv/lib/python3.8/site-packages/torch/nn/modules/module.py:1501: UserWarning: operator() profile_node %359 : int[] = prim::profile_ivalue[profile_failed="varying profile values"](%357)
 does not have profile information (Triggered internally at ../third_party/nvfuser/csrc/graph_fuser.cpp:104.)███████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.85s/it]
  return forward_call(*args, **kwargs)

**Comment by xuejiale929** [comment]
cuda11.8,驱动550.135

**Comment by ganfengbao** [comment]
+1 遇到了同样的问题，两个流式推理直接就卡死了，利用webui做测试的时候

**Comment by aluminumbox** [comment]
不要用webui并发推理，runtime里的grpc我是试过可以并发没问题的，其他的部分并发不是官方保证，如果一定要用gradio提供服务，那么需要自己研究一下
