### ISSUE TITLE
如很改成 ip运行

### ISSUE THREAD

**Issue by zkxmaster** [FunAudioLLM/CosyVoice#71]
python3 webui.py --port 50000 --model_dir pretrained_models/CosyVoice-300M   如何修改启动的host , 默认是本机访问，如很改成IP 访问

**Comment by cacard** [comment]
你为啥改IP？默认就能通过localhost或127.0.0.1或你的IP访问。

**Comment by xxxzsgxxx** [comment]
> 你为啥改IP？默认就能通过localhost或127.0.0.1或你的IP访问。

localhost和127.0.0.1可以，外网IP地址是不行的。

**Comment by lilongwei5054** [comment]
> 你为啥改IP？默认就能通过localhost或127.0.0.1或你的IP访问。

因为很多调试大模型的设备是专用的设备，一般配备高性能显卡，放在机房，不是自己的工作电脑，而我们一般是通过xshell远程调试的，因此无法通过localhost访问，所以希望在自己的工作电脑上能通过局域网类似192.168.x.x 来访问。

**Comment by hongdangshao** [comment]
demo.launch(server_name="0.0.0.0",...)

**Comment by xxxzsgxxx** [comment]
> demo.launch(server_name="0.0.0.0",...)

我也碰到了这个问题，demo.launch添加可以工作。

可以patch一下：

cat host.patch
169c169
<     demo.launch(server_name=args.host,server_port=args.port)
---
>     demo.launch(server_port=args.port)
180,185d179
<     parser.add_argument('--host',
<                     type=str,
<                     default='0.0.0.0',
<                     help='Specify the IP address to listen on. Default is 0.0.0.0.')
<

**Comment by hongdangshao** [comment]
I have got it!Thanks's.

**Comment by shrekzhao** [comment]
not use
