### ISSUE TITLE
能否在语音合成的同时出srt字幕，还是得合成完后再whisper识别出来呢？

### ISSUE THREAD

**Issue by bk111** [FunAudioLLM/CosyVoice#712]
能否在语音合成的同时出srt字幕，还是得合成完后再whisper识别出来呢？

**Comment by aluminumbox** [comment]
合成的内容和文本是对应的，可以自行处理

**Comment by Lennon-cheng** [comment]
@aluminumbox  TTS 后得到每个字对应的时间戳。这个是 只能后处理 whisper 识别后对应文本，还是说，模型哪个地方可以吐出时间戳？
