### ISSUE TITLE
CosyVoice2-0.5B does not have spk2info.pt

### ISSUE THREAD

**Issue by ZxnSnowy** [FunAudioLLM/CosyVoice#729]
I try to run webui.py, prompting that the variable sft_spk is an empty list, and then I find that spk2info.pt is not in the model

**Comment by IuvenisSapiens** [comment]
It seems like you're encountering an issue with the absence of the `spk2info.pt` file in the `pretrained_models\CosyVoice2-0.5B` directory, which is causing the `webui.py` script to report that the `sft_spk` variable is an empty list.
[spk2info.zip](https://github.com/user-attachments/files/18149385/spk2info.zip)

To resolve this, you should unzip the provided `spk2info.zip` file to obtain the `spk2info.pt` file. After extracting it, place the `spk2info.pt` file within the `pretrained_models/CosyVoice2-0.5B` directory. This file is essential for the model, as it contains critical speaker information required for its proper operation.

**Comment by aiwantaozi** [comment]
To provide a more seamless out-of-the-box experience like cosyvoice1, would it be possible to include a spk2info.pt file in the cosyvoice2 model files to handle built-in voices?
cosyvoice2's model files: https://modelscope.cn/models/iic/CosyVoice2-0.5B/files
cosyvoice1's model files: https://modelscope.cn/models/iic/CosyVoice-300M/files

**Comment by hildazzz** [comment]
> It appears that you're encountering an issue with the absence of the `spk2info.pt` file in the `pretrained_models\CosyVoice2-0.5B` directory, which is causing the `webui.py` script to report that the `sft_spk` variable is an empty list.
> 
> To resolve this, you should unzip the provided [spk2info.zip](https://github.com/user-attachments/files/18149385/spk2info.zip) file to obtain the `spk2info.pt` file. After extracting it, place the `spk2info.pt` file within the `pretrained_models/CosyVoice2-0.5B` directory. This file is essential for the model, as it contains critical speaker information required for its proper operation.

请问大佬，这里提供的spkinfo和v1版本的计算方式一样吗？对比两个spkinfo.pt发现数值不一样？
