### ISSUE TITLE
对数字的朗读效果不好

### ISSUE THREAD

**Issue by haochange** [FunAudioLLM/CosyVoice#73]
**Describe the bug**
包含较多数字，如12345678或者2022年12月29日，的句子，朗读效果差。

**Comment by aluminumbox** [comment]
this is due to frontend process. we will use wetextprocessing to replace it, or you can convert it to character manually. these cases cannot be numerated, so we will not focus on fixing these bug

**Comment by aluminumbox** [comment]
we have used wetextprocessing to replace ttsfrd, update the code and install requirements to see whether it fix the bug
