### ISSUE TITLE
webui页面运行声音克隆报错：

### ISSUE THREAD

**Issue by lonngxiang** [FunAudioLLM/CosyVoice#77]
实际已经安装了soundfile
 raise RuntimeError(f"{func.__module__}.{func.__name__} {message}")
RuntimeError: torchaudio.backend.soundfile_backend.info requires soundfile, but we failed to import it. Please check the installation of soundfile.

![image](https://github.com/FunAudioLLM/CosyVoice/assets/40717349/ad0c7e1f-b71e-4f76-9673-9ec096a126a2)

**Comment by aluminumbox** [comment]
can you import soundfile

**Comment by lonngxiang** [comment]
解决了，主要是环境中没有安装sox或soudfile，默认torchaudio需要底层linux sox支持，windows是soudfile要求；这里docker容器是ubuntu，所以安装即可
