### ISSUE TITLE
CosyVoice2 模型配置文件更新

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#779]
**Is your feature request related to a problem? Please describe.**
看论文里CosyVoice2应该是24Khz的，但是现在的example配置里还是22Khz呢，建议更新一下配置文件，以免混淆。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cpken** [comment]
因为 2.0 的训练脚本还没有提供出来，你看到的是 1.0 的训练脚本。

**Comment by JohnHerry** [comment]
收到，谢谢！ 持续学习中!

**Comment by JohnHerry** [comment]
> 因为 2.0 的训练脚本还没有提供出来，你看到的是 1.0 的训练脚本。

请教一下，就flow模型而言， CosyVoice2 和 CosyVoice1的训练配置，和训练脚本应该没有太大变化吧？
