### ISSUE TITLE
如果用WeTextProcessing的话，像 [laughter] 这种特殊符号还可以识别出来吗

### ISSUE THREAD

**Issue by KevinWang676** [FunAudioLLM/CosyVoice#78]
想问一下：如果用WeTextProcessing的话，像 [laughter] 这种特殊符号还可以识别出来吗？感谢！

**Comment by aluminumbox** [comment]
yes it will. you can try more example to see if there is any bug

**Comment by KevinWang676** [comment]
@aluminumbox Thanks for your reply. I tried to include [laughter] in my texts, however, the model could not recognize this symbol [laughter] and could not generate laughs. Can you help us resolve this issue? Thanks!

**Comment by aluminumbox** [comment]
> @aluminumbox Thanks for your reply. I tried to include [laughter] in my texts, however, the model could not recognize this symbol [laughter] and could not generate laughs. Can you help us resolve this issue? Thanks!

print normalized text in your code, check if [laughter] is kept. also remember use cosyvoice-300m-instruct model

**Comment by aluminumbox** [comment]
> @aluminumbox I see. So, only cosyvoice-300m-instruct supports fine-grained control like [laughter] and other models like cosyvoice-300m do not. Am I right? Thanks!

yes, check readme to learn how to use the 3 models
