### ISSUE TITLE
用预置语音生成（sft）inference会漏句

### ISSUE THREAD

**Issue by zzu-xcy** [FunAudioLLM/CosyVoice#8]
用预置语音生成（sft）inference会漏句，音色：中文女
输入：
那有哪些美剧是不太适合学英语的呢？我来给大家举几个例子吧。第一个《破产姐妹》，我不知道为什么总有人推荐这一部，我先声明一下，我真的很喜欢很喜欢破产姐妹，它真的很下饭。我大学有一段时间就是天天去食堂打包吃的，然后回到宿舍，我就边看边吃，甚至听到她那个片头曲，我就会很有食欲，但是我真的真的没有办法用它来学英语。**一个是语速太快了**；第二全是开车的台词，你说是生活中、考试试中哪儿会用到？所以我觉得破产姐妹下饭必备，学英语还是算了。

其中,  "一个是语速太快了"没有合成直接被跳过了

**Comment by ZhihaoDU** [comment]
建议可以尝试适当拆句之后再合成，比如这一段话拆成两段分别合成试试看

**Comment by Liujingxiu23** [comment]
@ZhihaoDU 请教下 SFT(比如使用5小时单发音人数据)，会导致鲁棒性下降，比如 重复、插入、替换错误的增多吗？如果不会，是通过何种方式解决的呢

**Comment by Pydataman** [comment]
mark

**Comment by aluminumbox** [comment]
> @ZhihaoDU 请教下 SFT(比如使用5小时单发音人数据)，会导致鲁棒性下降，比如 重复、插入、替换错误的增多吗？如果不会，是通过何种方式进行SFT的呢。比如设置学习率、batchsize有什么技巧吗

check example/libritts for sft training example, it will futher improve model performance on specific speaker
