### ISSUE TITLE
关于Instruction方面的问题

### ISSUE THREAD

**Issue by wkingqq** [FunAudioLLM/CosyVoice#84]
代码中这一部分有一个spk_id，请问用了这一个是不是说话人音色相当于被固定了？

**Comment by hoyden** [comment]
Instruction model里的spk_id应该没有实际生效，主要还是靠instruction来控制

**Comment by aluminumbox** [comment]
we will use spk id in instruct mode, but the instruct text can influence the spk identity, even change it

**Comment by wkingqq** [comment]
> Instruction model里的spk_id应该没有实际生效，主要还是靠instruction来控制

我测试的时候发现spk_id用英文男很容易出现性别混乱的问题
