### ISSUE TITLE
前端webui改为docker启动，

### ISSUE THREAD

**Issue by SilentTE** [FunAudioLLM/CosyVoice#85]
dockerfile是否可以参考server的写法,,使用相同的基础镜像?

**Comment by lonngxiang** [comment]
https://blog.csdn.net/weixin_42357472/article/details/140213547
可以的，仅供参考

**Comment by aluminumbox** [comment]
> dockerfile是否可以参考server的写法,,使用相同的基础镜像?

yes you can, check runtime/python/dockerfile and change cmd to python webui.py
