### ISSUE TITLE
Execute CosyVoice on the local deployment following the step-by-step instructions in ReadMe.md.  Cosyvoice fails to start.

### ISSUE THREAD

**Issue by zhanbei1** [FunAudioLLM/CosyVoice#86]
**Describe the bug**
Follow the instructions in README.md step by step, deploy on a personal server, execute
`python3 webui.py --port 50000 --model_dir speech_tts/CosyVoice-300M`
Unable to start, error reported.

After executing the startup command, all the logs are as follows (this is all the logs) :
`
2024-07-10 15:46:16, 963-modelscope-INFO-PyTorch version 2.0.1+cu118 Found.
The 15:46:16 2024-07-10, 964 - modelscope - INFO - Loading ast index from/root/cache/modelscope/ast_indexer

2024-07-10 15:46:17, 372-modelscope-INFO-Loading done! Current index file version is 1.15.0, with md5 9f4fb120384b6702f0cca427af528ecb and a total number of 980 components indexed
/ root/miniconda3 / envs/cosyvoice/lib/python3.8 / site - packages/torch / _jit_internal. Py: 726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now.  {}
warnings.warn(
Killed
`

**Expected behavior**
I want to deploy CosyVoice on my personal server and run it successfully.

**Screenshots**
<img width="1509" alt=" Screenshot 2024-07-10 15 52 23" src="https://github.com/FunAudioLLM/CosyVoice/assets/23068139/c3f40fef-af76-4a4b-b961-21edb41feeec">

<img width="1464" alt="截屏2024-07-10 15 57 47" src="https://github.com/FunAudioLLM/CosyVoice/assets/23068139/b1a2d02d-042d-4a39-a127-32b1c76aa423">

**Desktop (please complete the following information):**
- OS: centos7, 2-core 2G, new Alibaba cloud environment, no other services are deployed
- Version：Cosy Voice commit number is ：9aea393d18b633e06c2eb8df34a0e817dd11c403

**Additional context**
The first time it starts, an error is reported saying that a Tensorflow is missing. I installed it. After many times to start, will report the error, has been unable to start.
I don't have enough resources? Or is there something else that doesn't operate?
If resources are not enough, how do I add resources

**Comment by younger027** [comment]
你这个应该是内存爆了吧,被系统kill了

**Comment by zhanbei1** [comment]
> 你这个应该是内存爆了吧,被系统kill了

运行这个服务，最少的资源是多少？？

**Comment by aluminumbox** [comment]
> > 你这个应该是内存爆了吧,被系统kill了
> 
> 运行这个服务，最少的资源是多少？？

at least 16g memory

**Comment by zhanbei1** [comment]
> > > 你这个应该是内存爆了吧,被系统kill了
> > 
> > 
> > 运行这个服务，最少的资源是多少？？
> 
> at least 16g memory

OK，感谢评论，这个Issue我将会关闭

**Comment by wen0320** [comment]
如果说，我是说如果哈，我没有16G的GPU内存设备。我应该怎么优化呢？目前尝试了在代码中添加
torch.cuda.empty_cache()
也没有多大作用
