### ISSUE TITLE
Will FSQ and LFQ better when used in LLM based TTS?

### ISSUE THREAD

**Issue by JohnHerry** [FunAudioLLM/CosyVoice#88]
We are  following the TorToiseTTS like  LLM  projects.  Both TorToise and CosyVoice choosing the VQ as quantizer as I had read in papers,  while it is said that FSQ or LFQ makes less dead code.  Are there any proves that LFQ and FSQ do help LLM based tts training and inference?  Thanks for information about it, and we appreciate for more detailed explanation.

**Comment by aluminumbox** [comment]
@ZhihaoDU maybe can answer this question

**Comment by JohnHerry** [comment]
> According to my experiments, FSQ or LFQ indeed make less dead codes than the VQ, almost no dead codes. However, I haven't found an evidence that less dead code means better performance. Up to my knowledge, this is still an open question.

Thank you very much.
