### ISSUE TITLE
如何训练定制的spk2info.pt？

### ISSUE THREAD

**Issue by traddo** [FunAudioLLM/CosyVoice#94]
如题

**Comment by aluminumbox** [comment]
train your own sft model, save spk embedding in spk2info.pt

**Comment by traddo** [comment]
> train your own sft model, save spk embedding in spk2info.pt

直接用原厂模型是否可以提取speaker embedding?

**Comment by zhangyike** [comment]
> train your own sft model, save spk embedding in spk2info.pt

how to get a single spk embedding from spk2embedding.pt when the spk has many utts?

**Comment by aluminumbox** [comment]
> > train your own sft model, save spk embedding in spk2info.pt
> 
> how to get a single spk embedding from spk2embedding.pt when the spk has many utts?

simple mean, check tools/prepare_embedding.py for detail

**Comment by zhangyike** [comment]
> > > train your own sft model, save spk embedding in spk2info.pt
> > 
> > 
> > how to get a single spk embedding from spk2embedding.pt when the spk has many utts?
> 
> simple mean, check tools/prepare_embedding.py for detail

I cannot find  tools/prepare_embedding.py. I guess the "spk2embedding.pt" should regenerated as a single vector for each spk by average embeddings of the same spk by modifying "tool/extract_embeddings.py"

**Comment by traddo** [comment]
> > > > train your own sft model, save spk embedding in spk2info.pt
> > > 
> > > 
> > > how to get a single spk embedding from spk2embedding.pt when the spk has many utts?
> > 
> > 
> > simple mean, check tools/prepare_embedding.py for detail
> 
> I cannot find tools/prepare_embedding.py. I guess the "spk2embedding.pt" should regenerated as a single vector for each spk by average embeddings of the same spk by modifying "tool/extract_embeddings.py"

look examples/libritts/cosyvoice/run.sh, inference.py
