### ISSUE TITLE
supervised fine-tuning Flow and HIFT

### ISSUE THREAD

**Issue by zhangyike** [FunAudioLLM/CosyVoice#97]
It seems that supervised fine-tuning (SFT) for flow or HIFT modules uses ground-truth data. Specifically, speech tokens are derived from a speech tokenizer rather than from an SFTed LLM for flow SFT, and mel features are derived from real waveforms rather than from an SFTed flow for HIFT SFT. I wonder if only LLM SFT is necessary, or if flow/HIFT SFT with ground-truth data provides satisfactory results?

**Comment by aluminumbox** [comment]
we also support flow sft, but not hift sft, just change llm to flow in run.sh stage 5

**Comment by zhangyike** [comment]
> we also support flow sft, but not hift sft, just change llm to flow in run.sh stage 5

My question is inputs for flow sft are speech tokens generated from speech tokenizer rather than from the SFTed llm outputs. 
For example, given a training sample consisting of a wave and the corresponding text, speech_tokens can be obtained from the following ways:
speech_tokens1 = speech_tokenizer(wave)
speech_tokens2 = SFTed_LLM(text)
The released demo uses speech_tokens1 for flow SFT, but I think  using speech_tokens2 may be better.

**Comment by zhangyike** [comment]
The config in cosyvoice.yaml is proper to SFT?  max_frames_in_batch seems too small and max_epoch seem too large. Are these recommanded?  
batch: !name:cosyvoice.dataset.processor.batch
    max_frames_in_batch: 2000
train_conf:
    max_epoch: 200
`

**Comment by aluminumbox** [comment]
> The config in cosyvoice.yaml is proper to SFT? max_frames_in_batch seems too small and max_epoch seem too large. Are these recommanded? batch: !name:cosyvoice.dataset.processor.batch max_frames_in_batch: 2000 train_conf: max_epoch: 200 `

check cosyvoice.yaml change some hyperparameter according to annotation. you can increase max_frames if your cuda memory is enough
